### ISSUE TITLE
Unable to register for MAM with Conditional Access flow 

### ISSUE THREAD

**Issue by sandeepbhatia4922** [msintuneappsdk/ms-intune-app-sdk-android#106]
**Describe the bug:**
I have applied app protection policies in my app using Intune sdk and MSAL.  Everything is  working fine.  Protection policies are being delivered to app.  Now I am  going to test a Conditional Access auth flow with same app which is already policy managed app.
Note - App is not listed as an [Partner productivity apps]. We are targeting app protection policies using application id(Package Name)

With conditional access I, I never receive a `MsalIntuneAppProtectionPolicyRequiredException` event in the onError of my `AuthenticationCallback` . I always get  callback inside `onCancel()` method of `AuthenticationCallback.` So there is no way  to call `remediateCompliance` on the MAMComplianceManager.
As per sample app we can handle it inside `onError(exception: MsalException?) method` like this

```
class AuthCallback : AuthenticationCallback {
        override fun onSuccess(authenticationResult: IAuthenticationResult) {
            val account: IAccount = authenticationResult.account

            val upn = account.username
            val aadId = account.id
            val tenantId = account.tenantId
            val authorityURL = account.authority

            // Register the account for MAM.
            mEnrollmentManager?.registerAccountForMAM(upn, aadId, tenantId, authorityURL)
        }

        override fun onError(exception: MsalException?) {

            if (exception is MsalIntuneAppProtectionPolicyRequiredException) {

                // Note: An app that has enabled APP CA with Policy Assurance would need to pass these values to `remediateCompliance`.
                // For more information, see https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-ca-with-policy-assurance
                
            } else if (exception is MsalUserCancelException) {
              
            } else {
              
            }
        }

        override fun onCancel() { }
    }
```

The problem is I am getting callback inside `onCancel() `method

Expected behavior:

Expect the compliance errors to fire when requesting a token so I can engage the MAMComplianceManager flow per the Android App SDK docs

Screenshots and logs:

My Conditional Access policy:-
<img width="1785" alt="policy" src="https://user-images.githubusercontent.com/46603588/159498151-3008a5fb-da84-4a38-8aff-8b287e60f191.png">
<img width="1623" alt="Screenshot 2022-03-22 at 7 28 08 PM" src="https://user-images.githubusercontent.com/46603588/159498428-4e0be572-1d78-49c6-811f-b8d698974488.png">
<img width="594" alt="Screenshot 2022-03-22 at 7 29 14 PM" src="https://user-images.githubusercontent.com/46603588/159498637-f42bfdf4-2d55-495a-bb40-d90d9ee2ac6b.png">

App Behaviour :-
![App](https://user-images.githubusercontent.com/46603588/159498685-cb179558-7000-43c4-8152-33c6e7606042.jpg)

Protection policy targeted to app and status:-
<img width="1792" alt="Screenshot 2022-03-22 at 7 31 47 PM" src="https://user-images.githubusercontent.com/46603588/159499404-be6ef07e-9348-4bf0-86e7-8d27c6aceb19.png">

Smartphone (please complete the following information):

Device: OPPO CPH1937
OS: Android 11
Intune App SDK for Android (please complete the following information):

What version of the Intune SDK are you using? Are you using the latest version? 8.1.1
What platform is your app based in (Java, Xamarin based, Cordova, etc)?  java, kotlin

**Comment by sandeepbhatia4922** [comment]
@meghandaly Please look into this. Why i am unable to get aaid from `MsalIntuneAppProtectionPolicyRequiredException` ?
Please help....

**Comment by meghandaly** [comment]
@sandeepbhatia4922 can you please follow the directions to [collect Android logs](https://docs.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android) and share the incident ID?

We will need those to continue our investigation.

**Comment by sandeepbhatia4922** [comment]
Hi @meghandaly  This time I got upn, aadid, tenantId and authorityURL from `MsalIntuneAppProtectionPolicyRequiredException ` inside OnError() method. But calling 

`val complianceManager = MAMComponents.get(MAMComplianceManager::class.java) complianceManager?.remediateCompliance(upn, aaid, tenantis, authorityURL, true)`

abruptly closes my app. App remains in background. I have uploaded logs through company portal app
Incident ID --- UWBQ8QE7

**Comment by sandeepbhatia4922** [comment]
@meghandaly no reply or solution provided yet?

**Comment by meghandaly** [comment]
To clarify, the 2nd attempt remediated compliance successfully? If so, is your app still experiencing an issue?

Our team reviewed the logs provided via the incident IDs and we see no clear MAM errors. There is indication that the app crashed, but nothing pointing directly to MAM.

**Comment by codylund** [comment]
Closing issue to inactivity.
