### ISSUE TITLE
Unable to create app bundle for SDK 8.6.1

### ISSUE THREAD

**Issue by Nickjuh101** [msintuneappsdk/ms-intune-app-sdk-android#109]
**Describe the Bug:**
Unable to create app bundles for Intune flavors using SDK version 8.6.1.

**Logs:**
Cause: com.microsoft.intune.mam.client.view.MAMViewGroup not found. Are you missing a MAM support library dependency?
Step it occurs in: transformClassesWithMamifyTransformForProductionIntuneRelease

**To Reproduce:**
1. Navigate to Build > Generate Signed Bundle / APK
2. Choose Android App Bundle
3. Fill necessary credentials
4. Choose Intune build variant you want to create the bundle for
5. Finish

**Expected behavior:** 
Bundle is properly generated

**Versioning:**
MAM SDK version: 8.6.1
Platform: Android, Java
IDE: Android Studio
Target SDK: 31
MinSDK: 26
Project Gradle wrapper version: 7.2

CompileOptions:
- sourceCompatibility JavaVersion.VERSION_11
- targetCompatibility JavaVersion.VERSION_11

**Additional information:**
App does build for flavors that do not require/use the Intune SDK integration.
ViewGroup to MAMViewGroup conversion was added back in version 7.2.2. of the MAMSDK

**Comment by joakley-msft** [comment]
@Nickjuh101 we can try, but it's going to be difficult to proceed. Your "To Reproduce" steps aren't meaningful without the project that actually reproduces the problem.  I don't believe *every* app bundle project hits the issue you describe, so we need to know what specifically your project is doing.

1. Can you confirm you are positive that the MAM SDK AAR you are referencing from your build is 8.6.1, and not an older version? The build plugin jar and the SDK AAR must always be the same version -- never update one without the other.
2. Can you share all portions of your build.gradle file that configure the Intune plugin and dependencies.
3. Can you run the failing gradle task with the `--info` flag passed to Gradle on the command line and capture the output to a file. This log output *may* give us additional information.

**Comment by Nickjuh101** [comment]
@joakley-msft To confirm the first question I went over the project and found out there was a mistake made there. After updating properly the issue is resolved and I am able to create the necessary bundles. Thanks for your help. Ticket can be closed.
