### ISSUE TITLE
COMPANY_PORTAL_REQUIRED

### ISSUE THREAD

**Issue by dbsheta** [msintuneappsdk/ms-intune-app-sdk-android#11]
I'm trying out the Taskr demo app by changing client_id to native app in my aad. However, after login is completed, it always gives COMPANY_PORTAL_REQUIRED alert even though company portal is installed in the phone.

Im using Android Studio 3.2, Gradle version: 3.2.0-rc02. 
Changed compileSdkVersion and targetSdkVersion to 28 in place of 27.

**Comment by madhu-aithal** [comment]
I am also facing similar issue.

**Comment by dbsheta** [comment]
Error because of android:testOnly flag being true by default
