### ISSUE TITLE
NON_INTEGRATED_VIEW on android.widget.TextView

### ISSUE THREAD

**Issue by Innova133** [msintuneappsdk/ms-intune-app-sdk-android#110]
**Describe the bug:**
When running my application (debug build, strict mode enabled), I am getting a NON_INTEGRATED_VIEW on certain TextViews.

**To Reproduce**
I am not exactly sure, I have other projects where this does not happen.  I am looking for guidance on things to check for and to understand why this class is not getting mamified by the plugin.

**Expected behavior:**
I do not expect this exception to be thrown

**Screenshots and logs:**
Uncaught exception in app
    com.microsoft.intune.mam.client.strict.MAMStrictModeCheckFailedError: MAM Strict Mode check NON_INTEGRATED_VIEW failed. View android.widget.TextView in activity ...MainActivity is not MAM integrated, but should be. Are you using the build plugin and including necessary external libraries?
        at com.microsoft.intune.mam.client.strict.MAMStrictEnforcement.checkFailed(:191)
        at com.microsoft.intune.mam.client.strict.MAMStrictEnforcement.check(:205)
        at com.microsoft.intune.mam.client.strict.MAMStrictEnforcement.checkViews(:511)
        at com.microsoft.intune.mam.client.app.ActivityBehaviorImpl.onResume(:421)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(:88)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy17.onResume(Unknown Source)
        at com.microsoft.intune.mam.client.app.MAMActivity.onResume(MAMActivity.java:106)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1456)
        at android.app.Activity.performResume(Activity.java:8135)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4434)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4476)
        at android.app.servertransaction.ResumeActivityItem.execute(ResumeActivityItem.java:52)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Smartphone (please complete the following information):**
 - Device: Pixel 2 XL
 - OS: Android 12
 
**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using?  8.6.1 Are you using the latest version? Yes
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?  Java (mostly Kotlin)
- For errors during build, does the app build without Intune SDK integration?  Build is fine with or without Intune, runtime error.
- For errors post build, does the app launch without being Intune SDK integrated?  Yes.
- Who is the customer?  
- Do you see a trend with it only being reproduced on a specific device?  No

**Additional context:**

**Comment by joakley-msft** [comment]
Hi @Innova133, thanks for reporting this. The most straightforward way for us to investigate this will be if you're able to provide a sample project that reproduces the issue, in which case we can take the investigation from there. If that's not possible, we can try to isolate the view that's causing the problem and talk through what might be wrong.

When MAM policy is applied / the Company Portal is installed, MAM will dynamically replace occurrences of android.widget.TextView with a class called MAMTextView, and apparently that's not happening as expected here.
1. Is the activity producing the error displaying multiple text views? If so, are others replaced with MAMTextView or are there multiple views affected? Layout Inspector (https://developer.android.com/studio/debug/layout-inspector) may be helpful in answering this question.
2. How is the TextView created? Is it inflated from layout xml or is it constructed programmatically?
3. If you're inflating from xml, do you override the layout inflater or onCreateView method?

**Comment by Innova133** [comment]
Thanks for the response @joakley-msft .  Sorry for the delay getting back, I was on vacation for a few days :)

> Hi @Innova133, thanks for reporting this. The most straightforward way for us to investigate this will be if you're able to provide a sample project that reproduces the issue, in which case we can take the investigation from there. If that's not possible, we can try to isolate the view that's causing the problem and talk through what might be wrong.
> 

Let's first try to isolate the issue.

> When MAM policy is applied / the Company Portal is installed, MAM will dynamically replace occurrences of android.widget.TextView with a class called MAMTextView, and apparently that's not happening as expected here.
> 
> 1. Is the activity producing the error displaying multiple text views? If so, are others replaced with MAMTextView or are there multiple views affected? Layout Inspector (https://developer.android.com/studio/debug/layout-inspector) may be helpful in answering this question.

Yes, there are quite a few TextViews in this activity.  Using Layout Inspector, the are all AppCompatTextViews.....There are 0 TextViews and 0 MAMTextViews in the activity as far as I can tell.

> 2. How is the TextView created? Is it inflated from layout xml or is it constructed programmatically?

All of the TextViews are inflated from xml layout.


> 3. If you're inflating from xml, do you override the layout inflater or onCreateView method?

No.

As a note, one of our other applications that is working fine, is also showing all AppCompatTextViews in Layout Inspector.

**Comment by bannus** [comment]
@Innova133, based on your response your setup seems pretty standard, so unfortunately there's not much to work from there. Could you try enabling both the `report` and `verify` options for the MAM build plugin (see [docs](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#reporting))? Please share the report from `outputs/logs`.

If those logs don't turn up anything useful, a sample project that reproduces the issue would likely be the best way for us to diagnose this.

**Comment by joakley-msft** [comment]
As a side note, we'd expect the MAM build plugin to modify AppCompatTextView itself. It sounds as though that's likely not happening, but we'll need (ideally) a sample project reproducing the problem or at least the logs Bannus mentioned to diagnose further.

**Comment by joakley-msft** [comment]
It would be the former as the AppCompatTextView class itself would be rewritten to extend MAMTextView instead of TextView.

**Comment by Innova133** [comment]
Ok, so I made a kotlin extension method to print out the class hierarchy.  I disabled MAMStrictMode so that my app would no longer crash.  I then printed out the hierarchy of all the TextViews in my activity.   They all extend MAMTextView like this:

`E/ExtensionsKt: androidx.appcompat.widget.AppCompatTextView`
`E/ExtensionsKt:   com.microsoft.intune.mam.client.widget.MAMTextView`
`E/ExtensionsKt: 	android.widget.TextView`
`E/ExtensionsKt: 		android.view.View`
`E/ExtensionsKt: 			java.lang.Object`


Is there any way to know WHICH textView is not MAM Integrated?

**Comment by Innova133** [comment]
[IntuneReport.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/8818603/IntuneReport.zip)

Is this helpful?

**Comment by Innova133** [comment]
Min is 24, target is 32.

**Comment by bannus** [comment]
Hi @Innova133, unfortunately both the report and the `TextView` hierarchy in your [previous response](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/110#issuecomment-1143684773) suggest that the plugin is rewriting the parent of `AppCompatTextView` to `MAMTextView`.

I did notice that the original report said that the offending view was a `android.widget.TextView`, not `androidx.appcompat.widget.AppCompatTextView`. Is it possible that there is a `TextView` in your `MainActivity` that you haven't accounted for? If you're unable to turn up anything, a sample project that reproduces the issue may be our only route forward.

**Comment by meghandaly** [comment]
@Innova133 any updates on Bannus' ask?

**Comment by Innova133** [comment]
At this time I have moved on to work on a different app.  I did not find any TextView's in my project anywhere, all were AppCompatTextView.  If you would like, you can close this issue, and if I experience it again in the future (with a project that I can share) I will open a new one.
