### ISSUE TITLE
OutOfMemoryError When executeHttpSend

### ISSUE THREAD

**Issue by Nash123-start** [msintuneappsdk/ms-intune-app-sdk-android#111]
Fatal Exception: java.lang.OutOfMemoryError
Failed to allocate a 4126736 byte allocation with 987360 free bytes and 964KB until OOM, target footprint 268435456, growth limit 268435456

........

com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.executeHttpSend (UrlConnectionHttpClient.java:5)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.access$100 (UrlConnectionHttpClient.java:1)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call (UrlConnectionHttpClient.java:2)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient$2.call (UrlConnectionHttpClient.java:1)
com.microsoft.identity.common.internal.net.NoRetryPolicy.attempt (NoRetryPolicy.java:2)
com.microsoft.identity.common.internal.net.NoRetryPolicy.attempt (NoRetryPolicy.java:1)
com.microsoft.identity.common.internal.net.UrlConnectionHttpClient.method (UrlConnectionHttpClient.java:3)
com.microsoft.identity.common.internal.net.AbstractHttpClient.get (AbstractHttpClient.java:1)
com.microsoft.identity.common.internal.providers.microsoft.azureactivedirectory.AzureActiveDirectory.performCloudDiscovery (AzureActiveDirectory.java:7)
com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.loadCloudDiscoveryMetadata (AdalMigrationAdapter.java:2)
com.microsoft.identity.common.internal.migration.AdalMigrationAdapter.adapt (AdalMigrationAdapter.java:5)
com.microsoft.identity.common.internal.migration.TokenMigrationUtility$1.run (TokenMigrationUtility.java:1)

**Comment by bannus** [comment]
Please re-open new issue with all information requested in "bug report" template.
