### ISSUE TITLE
[Question]Does the Intune SDK get the credentials for the portal site app?

### ISSUE THREAD

**Issue by pa-hisayuki-kishino** [msintuneappsdk/ms-intune-app-sdk-android#114]
**Describe the question:**
It's a simple question about how it works.
Do you have the following recognition?
For apps that incorporate the Intune SDK, the Microsoft credentials obtained from the portal site app (broker app) are used via the Intune SDK, so the app protection policy can be obtained.

※When I contacted the Intune Support Center, I was informed.

**Comment by bannus** [comment]
Hi @pa-hisayuki-kishino, I don't fully understand your question, but I can point you at our docs which describe the changes SDK integrators need to make to facilitate delivery of App Protection Policy: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#account-authentication
