### ISSUE TITLE
On reinstall SDK posts ENROLLMENT_SUCCEEDED notification

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-android#118]
**Describe the bug:**
Once Intune enrollment is successful. And we uninstall and reinstall the app.
Then SDK posts ENROLLMENT_SUCCEEDED notification immediately after app launch.
This happens only with release build type not with debug.

**Smartphone:**
 - Android 10.0 (Haven't tried on other Android versions)

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
8.3.0

- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Java, Android native

**Comment by codylund** [comment]
This behavior is by design. The enrollment is tracked on the Company Portal side and, following a reinstall, your app will automatically become reenrolled based on that state.

**Comment by parveen-bhatia** [comment]
Thanks for clarifications. 
Follow up question on that  - 

**Q:** Is there any way to get `upn` after reinstall (when we receive enrollment sucess) without authenticating with Azure AD again ? (Because i think to [retrieve app config policies](https://msintuneappsdk.github.io/ms-intune-app-sdk-android/reference/com/microsoft/intune/mam/policy/appconfig/MAMAppConfigManager.html#getAppConfig(java.lang.String)) `upn` is required)

**Comment by parveen-bhatia** [comment]
@codylund in this case when app is reinstalled and enrollment is successful from SDK. Then should we still continue user with MSAL authentication flow and then enrollment with intune ?
