### ISSUE TITLE
Policy refresh callback is getting invoked even no protection policies are configured

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-android#122]
**Describe the bug:**
When we don't configure any app protection policies in the intune console and only app config policies are configured.
Then once Intune enrollment is successful from the app. Then we are getting callback for notification `MAMNotificationType.REFRESH_POLICY`

Smartphone:
Android 10.0 (Haven't tried on other Android versions)

Intune App SDK for Android (please complete the following information):
What version of the Intune SDK are you using? Are you using the latest version?
8.3.0

What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Java, Android native

**Comment by microsoftjoe** [comment]
Hi @parveen-bhatia,
Sorry for the confusion, this is by design.
The Intune service, for its own reasons, will deliver some things that we think of as "policy" in the app-config channel. Because of this, we need to send a REFRESH_POLICY notification when we detect a change to app config.
