### ISSUE TITLE
On enrolling with intune no notifications results are received if no policies and no company portal app

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-android#124]
Describe the bug:
When we don't have Company portal app installed and no intune policies are configured.
Then on first time calling `enrollmentManager?.registerAccountForMAM` we are getting notification with result `NOT_LICENSED`
But subsequent calls to`enrollmentManager?.registerAccountForMAM` doesn't return with any notification result.

Smartphone:
Android 10.0 (Haven't tried on other Android versions)

Intune App SDK for Android (please complete the following information):
What version of the Intune SDK are you using? Are you using the latest version?
8.3.0

What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Java, Android native

**Comment by meghandaly** [comment]
@parveen-bhatia Can you please indicate what behavior you expect?

MAM policies cannot be enforced without the presence of the Company Portal so it is not clear to me what scenario you are attempting to test. For more information, please refer to the [documentation](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#company-portal-app).

**Comment by parveen-bhatia** [comment]
Scenario is user forgot to install company portal app and there are no intune policies. 
Then if user tries to enroll with intune using `enrollmentManager?.registerAccountForMAM` then SDK sends `NOT_LICENSED` only first time. Next time if user tries to enroll then SDK doesn't send any notification. So, in our case we wait for enrollment result notification from SDK to proceed further. But as no notification is being thrown from SDK, user just keeps on waiting (like showing spinner till enrollment status is received)

**Comment by meghandaly** [comment]
What you are describing is not a realistic scenario.

If the user forgot to install the Company Portal and there were Intune policies applied, they would be prompted to do so before they can access the application. 

From our documentation:

> <html>
<body>


NOT_LICENSED | The user is not licensed for Intune, or the attempt to contact the Intune MAM service failed. The app should continue in an unmanaged (normal) state and the user should not be blocked. Enrollments will be retried periodically in case the user becomes licensed in the future.
-- | --



</body>
</html>

To understand the interval at which `NOT_LICENSED` is received from the SDK please see the [Delivery Timing Summary](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-delivery#delivery-timing-summary) for "User Not Licensed".

Ultimately, I suspect there is an underlying issue with your app integration. 

Please refer to the [Microsoft Intune App SDK for Android developer guide](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android) and the [Taskr Sample App](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App) for further guidance.

**Comment by parveen-bhatia** [comment]
Thanks for your response.

In case company portal is not installed but policies exist then we are getting prompt to install company portal.
But if there are no policies and company portal is not installed then we are not getting any prompt from SDK.
And we don't want the user to continue use the app in unmanaged state. And we already followed instructions from dev guide.

**Comment by meghandaly** [comment]
Based on your desired scenario it sounds like you want to implement [App Protection CA](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-protection-ca).
