### ISSUE TITLE
Add support for React Native

### ISSUE THREAD

**Issue by rturk** [msintuneappsdk/ms-intune-app-sdk-android#13]
Please Add support for React Native based Apps

**Comment by msintuneappsdk** [comment]
The Intune SDK development team actively tests and maintains support for apps built with the native Android, iOS (Obj-C, Swift), Xamarin, Xamarin.Forms, and Cordova platforms. While some customers have had success with Intune SDK integration with other platforms such as React Native and NativeScript, we do not provide explicit guidance or plugins for app developers using anything other than our supported platforms.

For React Native, we support gradle-based builds.

**Comment by dgrover-spotnana** [comment]
Hey @msft-cofitz , any plans on supporting React Native in near future ?
