### ISSUE TITLE
Intune sdk conflict with androidx.fragment:fragment:1.5.1 library and cause launch crash

### ISSUE THREAD

**Issue by yjp123456** [msintuneappsdk/ms-intune-app-sdk-android#130]
Bug description:
After the Android X version is upgraded to 1.5, the method call of "lifecycle.addObserver(new Recreator(mOwner))" is moved to the parameterless constructor of componentactivity. This will cause the intune hook the onCreate method of the launch activity without executing the method call of "mSavedStateRegistryController.performRestore(savedInstanceState)" originally in componentactivity - > onCreate, which ultimately leads to  Initialization crash on  the method call of " Bundle bundle = mOwner.getSavedStateRegistry().consumeRestoredStateForKey(COMPONENT_KEY)" in Recreator -> onStateChanged

1. upgrade androidx.fragment:fragment version to 1.5.1
2. Integrated intune SDK  8.6.1
3. launch main activity which extends ComponentActivity
4. Try more time as it is not necessary present, depending on whether the execution time of the startup page is fast enough

Expected behavior:
crash with log: 
IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component

**Comment by mcsimons** [comment]
Hi, thanks for the report. In order to best investigate this, we require a bit more information. 
1. What version of androidx:fragment was your app previously one and was it successfully integrated with Intune?
2. Could you share the code snippets you are talking through in the bug description?
3. For the quickest investigation, could you provide a small sample app that reproduces this issue?

**Comment by mick1418** [comment]
I'm encountering the same issue when migrating androidx fragment:fragment from 1.4.0 to 1.5.2 with intune SDK 9.0.0.
It was working previously but now I have the same error message as in the description.

**Comment by mcsimons** [comment]
Thanks for the report, we are currently tracking this issue internally (Bug 15545854) and will update here.

**Comment by MathieuCalba** [comment]
Hello, we also face the same issue, but we can’t downgrade `androidx:fragment` as other libraries depends on newest version…

**Comment by davidalgar** [comment]
We are seeing the same issue. After forcing androidx.fragment:fragment to 1.4.0 and we still saw the issue - so I believe it may be another dependency update causing the issue, and updating fragment to 1.5.3 is just one way to encounter this issue.

**Comment by ahimberg** [comment]
I think that the Fragment upgrade is giving you a savedstate update to 1.2.0, (from 1.1.0, which didn't initialize in the way that conflicts with intune sdk).  This change in savedstate between 1.1 and 1.2 : https://github.com/androidx/androidx/commit/65bc2f4f74f8167f85de0003095e21b6144974a5

**Comment by bannus** [comment]
Evidence suggests there is an incompatibility between the current Intune SDK and `androidx.lifecycle:lifecycle-runtime` 2.5.0+. (Updating to `androidx.fragment:fragment` 1.5.0+ will include a transitive dependency update from for `androidx.lifecycle:lifecycle-*` from 2.3.1 to 2.5.0+.)

We are working on a fix that will become available in the next SDK release. In the meantime, please remain on older versions of any `android` libraries that would pull in `androidx.lifecycle:lifecycle-runtime` 2.5.0+. (You could also try setting a [forced version](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html) of `androidx.lifecycle:lifecycle-runtime`, but this has not been tested and may lead to other bad interactions.)

**Comment by bblia** [comment]
@bannus is there a rouge ETA for an SDK update?

**Comment by bannus** [comment]
This will be fixed in the next release of the Intune SDK, due mid-November.

**Comment by msft-cofitz** [comment]
Fixed in [SDK 9.1.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/9.1.0)
