### ISSUE TITLE
App crashes due to PendingIntent(Android)

### ISSUE THREAD

**Issue by mauryaRahul2** [msintuneappsdk/ms-intune-app-sdk-android#141]
**Describe the bug:**

**To Reproduce**
1. Make API level 31 or plus in Gradle.
2. Use java 11. 
3. Run the app 

**Expected behavior:**
We have a splash screen and on the same screen, we open intune login screen after the success of intune login screen we use the local login screen.
Above mentioned flow is working with android API level 30 and below but when I start using for above API level of 30 issue occur 

**Screenshots and logs:**
- Error log:
E  FATAL EXCEPTION: pool-13-thread-1
Process: com.mahindra.meconnect, 
          java.lang.IllegalArgumentException: com.mahindra.meconnect: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
                                                                                                    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
                                                                                                    	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
                                                                                                    	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
                                                                                                    	at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
                                                                                                    	at com.microsoft.intune.mam.client.app.MAMPendingIntent.getBroadcast(MAMPendingIntent.java:149)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:196)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:128)
                                                                                                    	at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:93)
                                                                                                    	at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:91)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Smartphone (please complete the following information):**
 - Device: [XIA0MI 11T PRO 5G]

**Intune App SDK for Android (please complete the following information):**
- Intune SDK version 9.1.0
- Kotlin and Java
- Organisation employee 
- It reproduces on each and every device

**Comment by mcsimons** [comment]
Hello, thanks for the report. Could you please confirm that you have properly tagged the Intents in your app in accordance with this documentation? - https://developer.android.com/about/versions/12/behavior-changes-12#pending-intent-mutability

**Comment by mauryaRahul2** [comment]
I have tried using mutable and immutable flags for my local code it was still giving an error in the provided log you can see it straight away throws an error for MAM sdk

**Comment by mauryaRahul2** [comment]
Caused by: java.lang.ClassNotFoundException: Didn't find class "cz.msebera.android.httpclient.client.utils.URIBuilder" 

	at com.mahindra.meconnect.authentication.MSALUtil.initializeMsalClientApplication(MSALUtil.java:227)
                 	at com.mahindra.meconnect.authentication.MSALUtil.acquireToken(MSALUtil.java:55)

also getting this error

**Comment by mauryaRahul2** [comment]
MSALUtil.acquireToken(SplashActivity.this, MSAL_SCOPES, loginHint, new AuthCallback());
<img width="1279" alt="Screenshot 2022-12-15 at 3 07 05 PM" src="https://user-images.githubusercontent.com/120377744/207824982-b52ac1b9-8430-4799-a535-57df43f6bb2f.png">

**Comment by mauryaRahul2** [comment]
com.microsoft.identity.common.exception.BaseException
this the excetion i got

**Comment by meghandaly** [comment]
@mauryaRahul2 

After another review of your stack it appears that the error is originating in the Android X `WorkManager` library.
What version of the `WorkManager` (androidx.work) are you referencing in your app? 

According to the Google documentation, [version 2.60 is not compatible with Android S targeting](https://developer.android.com/jetpack/androidx/releases/work#version_260_3) and [support is first introduced in version 2.70](https://developer.android.com/jetpack/androidx/releases/work#version_27_2).

> Version 2.7.0
> Note: WorkManager Version 2.7.0 is required for apps targeting Android 12 (S).

> Version 2.6.0
> Note: WorkManager Version 2.6.0 is not compatible for apps targeting Android 12 (S). You should be using version 2.7.0 instead.

If that does not resolve the issue, can you please [collect the Company Portal logs](https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-microsoft-android) from your device and share with us the PowerLift ID?

In regards to the additional error, I would not expect the `cz.msebera.android.httpclient.client.utils.URIBuilder` error to be related to the MAM SDK although it may be related to your MSAL usage, especially considering the exception `com.microsoft.identity.common.exception.BaseException` is from `com.microsoft.identity`.

Can you please investigate further and open a separate issue if you find my analysis to be incorrect?

**Comment by mauryaRahul2** [comment]
Thanks for the update

From: Meghan Daly - MSFT ***@***.***>
Date: Friday, 23 December 2022 at 12:03 AM
To: msintuneappsdk/ms-intune-app-sdk-android ***@***.***>
Cc: MAURYA RAHUL ***@***.***>, Mention ***@***.***>
Subject: Re: [msintuneappsdk/ms-intune-app-sdk-android] App crashes due to PendingIntent(Android) (Issue #141)
CAUTION: This email originated from outside of the Mahindra organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@mauryaRahul2<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FmauryaRahul2&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802342752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2Bitg41OZpPYUQ4WDXgFbRyJTMmPYlVXHU4IIoFbwWaU%3D&reserved=0>

After another review of your stack it appears that the error is originating in the Android X WorkManager library.
What version of the WorkManager (androidx.work) are you referencing in your app?

According to the Google documentation, version 2.60 is not compatible with Android S targeting<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.android.com%2Fjetpack%2Fandroidx%2Freleases%2Fwork%23version_260_3&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802342752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o%2Fb3T6daL0Md%2FO7d8D%2BYObuaNsK5lPDs5yxD106kpjs%3D&reserved=0> and support is first introduced in version 2.70<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdeveloper.android.com%2Fjetpack%2Fandroidx%2Freleases%2Fwork%23version_27_2&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802342752%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=o%2F3tuJ4f1BL5de7rXS%2FioCs4NKQasvxwGUeO%2B%2BQ43rQ%3D&reserved=0>.

Version 2.7.0
Note: WorkManager Version 2.7.0 is required for apps targeting Android 12 (S).

Version 2.6.0
Note: WorkManager Version 2.6.0 is not compatible for apps targeting Android 12 (S). You should be using version 2.7.0 instead.

If that does not resolve the issue, can you please collect the Company Portal logs<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Flearn.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fuser-help%2Fsend-logs-to-microsoft-android&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802498997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RekCtQaF8zxUP3Q3A850Ji695PHyaGVStSxHYfwnnN4%3D&reserved=0> from your device and share with us the PowerLift ID?

In regards to the additional error, I would not expect the cz.msebera.android.httpclient.client.utils.URIBuilder error to be related to the MAM SDK although it may be related to your MSAL usage, especially considering the exception com.microsoft.identity.common.exception.BaseException is from com.microsoft.identity.

Can you please investigate further and open a separate issue if you find my analysis to be incorrect?

—
Reply to this email directly, view it on GitHub<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmsintuneappsdk%2Fms-intune-app-sdk-android%2Fissues%2F141%23issuecomment-1363216207&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802498997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qxvyLz3WlGnr00R3ss0hLZStEpmHX0f51jsq2oe49Lc%3D&reserved=0>, or unsubscribe<https://apc01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA4WNDEGTHTGYTOTM32DBA4TWOSNFLANCNFSM6AAAAAAS3ZMBV4&data=05%7C01%7Cmaurya.rahul2%40mahindra.com%7C668ec76544e14b0524dd08dae44af18f%7C8c4858b5f020483ab7ef71ded6e81767%7C0%7C0%7C638073307802498997%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=9HO85lVX9DX2PGZ5OM8dkZaI%2FwHZ0jkk53xe%2F%2BQ%2FhKU%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

________________________________

---DISCLAIMER---------------------------------------------------------------------------- The contents of this E-mail (including the contents of the enclosure/(s) or attachment/(s) if any) are privileged and confidential material of Mahindra and Mahindra Limited (M&M) and should not be disclosed to, used by or copied in any manner by anyone other than the intended addressee/(s). If this E-mail (including the enclosure/(s) or attachment/(s) if any ) has been received in error, please advise the sender immediately and delete it from your system. The views expressed in this E-mail message (including the enclosure/(s) or attachment/(s) if any) are those of the individual sender. ------------------------------------------------------------------------------------------

**Comment by meghandaly** [comment]
@mauryaRahul2 can you update us as to the state of this issue? We would like to resolve it if you are no longer affected.

**Comment by naquee-rizwan** [comment]
Hi @meghandaly, we are also observing similar crash at our end with the following stacktrace :-

```
android.app.PendingIntent.checkFlags (PendingIntent.java:377)
android.app.PendingIntent.getActivityAsUser (PendingIntent.java:460)
android.app.PendingIntent.getActivity (PendingIntent.java:446)
android.app.PendingIntent.getActivity (PendingIntent.java:410)
com.microsoft.intune.mam.client.app.MAMPendingIntent.getActivity (MAMPendingIntent.java:9)
com.google.android.gms.common.api.GoogleApiActivity.zaa (GoogleApiActivity.java:8)
com.google.android.gms.common.GoogleApiAvailability.zaa (GoogleApiAvailability.java:11)
com.google.android.gms.common.api.internal.GoogleApiManager.zac (GoogleApiManager.java:4)
com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed (GoogleApiManager.java:68)
com.google.android.gms.common.api.internal.GoogleApiManager$zaa.connect (GoogleApiManager.java:52)
com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zaa (GoogleApiManager.java:54)
com.google.android.gms.common.api.internal.GoogleApiManager.handleMessage (GoogleApiManager.java:534)
android.os.Handler.dispatchMessage (Handler.java:107)
com.google.android.gms.internal.base.zar.dispatchMessage (zar.java)
android.os.Looper.loopOnce (Looper.java:238)
android.os.Looper.loop (Looper.java:357)
android.os.HandlerThread.run (HandlerThread.java:85)
```

From stack-trace, it seems as if GoogleApiManager / GoogleApiActivity are not passing Immutable / Mutable flags on the integrated library version which when resolved to MAMPendingIntent is resulting to this crash in our case.
Kindly confirm if my understanding of resolution to MAMPendingIntent is correct or not?
