### ISSUE TITLE
Null Pointer Exception while building app

### ISSUE THREAD

**Issue by SACHDEVHITESH** [msintuneappsdk/ms-intune-app-sdk-android#146]
Post integrating the SDK and trying to build the app the app build is failing with the following error during mamifying the classes

> Task :library:transformClassesWithMamifyTransformForBetaDebug FAILED

Execution failed for task ':library:transformClassesWithMamifyTransformForBetaDebug'.
> java.lang.NullPointerException

**Comment by bannus** [comment]
Not enough information -- please create a new issue which fills out the bug report template and includes logs.
