### ISSUE TITLE
Not compatible with Android Gradle plugin 3.3.0

### ISSUE THREAD

**Issue by kskumar** [msintuneappsdk/ms-intune-app-sdk-android#15]
When trying to build an app using Android Gradle plugin v3.3.0 and Gradle v4.10.1, the following error occurs:

`ERROR: class "com.microsoft.intune.mam.MamifyConfiguration_Decorated"'s signer information does not match signer information of other classes in the same package`

The same app compiles fine with Gradle plugin v3.2.1 and Gradle v4.6.

**Comment by msintuneappsdk** [comment]
This should be fixed in a version after Intune SDK for Android v. 4.8+
