### ISSUE TITLE
MAMEnrollmentManager.getRegisteredAccountStatus() deprecated without notes

### ISSUE THREAD

**Issue by ZacSweers** [msintuneappsdk/ms-intune-app-sdk-android#154]
**Describe the bug:**
This method was deprecated but is undocumented and has no instructions in the release notes.

In decompiled bytecode, it just calls through to a new overload with an extra (undocumented) string parameter with a `null` value.

<img width="980" alt="image" src="https://user-images.githubusercontent.com/1361086/221713301-3d51fad8-03a3-4478-9bf1-34e96625cb12.png">

However, this appears to break that method's contract as the parameter is annotated as `@NonNull` and emits a warning. As such, we cannot call it from Kotlin with a null value either and are left using the deprecated call.

I see the message refers to an `OID`, but it's not clear what that is.

**To Reproduce**
N/A

**Expected behavior:**
I would expect deprecations to have documented replacements/migrations.

**Screenshots and logs:**
N/A

**Smartphone (please complete the following information):**
N/A

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 9.4
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Java
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? N/A
- Do you see a trend with it only being reproduced on a specific device? N/A

**Additional context:**

**Comment by microsoftjoe** [comment]
Hi Zac, you are correct that there was a miss in the documentation for these methods. Sorry about that. The MAM integration guide will be updated in the next release.
In the meantime, you should use the new methods, passing the same value for "aadId" that you used when you originally registered the account. "OID" is a more technically correct term for what we have been calling "aadId", sorry for any confusion about that.
