### ISSUE TITLE
Feedback on the new preview plugin

### ISSUE THREAD

**Issue by ZacSweers** [msintuneappsdk/ms-intune-app-sdk-android#156]
Hi! While the new preview plugin is closed source, I took a look through decompiled class files and have feedback.

- The use of `MamifyClassesTask.this.getProject().getLogger()` in `MamifyClassesTask` is not compatible with configuration cache. Tasks expose a `getLogger()` API directly, you should use that.
- `intermediateOutputRoot` in `MamifyAllArtifactsPlugin.apply` should use project layout APIs. I.e. instead of `new File(project.getBuildDir(), "intermediates/intune/" + variant.getName())` it should be `project.getLayout().getBuildDirectory().dir("intermediates/intune/" + variant.getName()))`. The same should be done with setting the `getReportOutputDirectory` property.
- `onVariants` in `MamifyAllArtifactsPlugin` is called with only `components.selector()`, which is an error. It should call it with `.all()` or some sort of explicit filter.
- You should use AGP's extension API to have users _opt in_ variants to mamification rather than exposing your own `excludeVariants` property. This is racy at best due to configuration, and this new API exists for this reason. Here's an example based on how we do it in [keeper](https://github.com/slackhq/keeper).
  ```kotlin
  // User configuration
  androidComponents {
    beforeVariants { builder ->
      if (builder.flavorName == "intune") {
        builder.registerExtension(IntuneVariantMarker.class, KeeperVariantMarker.INSTANCE)
      }
    }
  }
  
  // Plugin code
  androidComponents {
    onVariants(selector().all()) { appVariant ->
      val extension = appVariant.getExtension(IntuneVariantMarker::class.java)
      if (extension != null) {
        // This variant is opted in, continue setting up mam
      }
    }
  }
  ```
- `GradleUtils.getClasspath()` should be entirely replaced with just using the variant's `runtimeConfiguration`. This is an API on variants received in `onVariants`. It should not be used directly however, but rather this configuration's files should be made into a `ConfigurableFileCollection` input property to the task. You can find an example in Keeper [here](https://github.com/slackhq/keeper/blob/b2847d74cc9f80b275a56efbda94c310ff7b668b/keeper-gradle-plugin/src/main/java/com/slack/keeper/KeeperPlugin.kt#L396).
- All input file properties should be denoted with a `@PathSensitivity` annotation to be properly cacheable. Currently none have this annotation.
- `getConfiguration()` should either be annotated with `@Nested` or be inlined away to forward properties from the extension.
- The plugin should use Gradle Worker APIs so that they can be configured in parallel.
- The plugin should consider using [ZipFlinger](https://android.googlesource.com/platform/tools/base/+/refs/heads/mirror-goog-studio-master-dev/zipflinger/) (part of AGP) to improve performance when creating jars.
- `getIntermediateOutputFiles()` and `getIntermediateOutputDirectories()` are computed seemingly from inputs, which almost certainly does not work as intended as the fields are initialized eagerly and before the inputs are set. I suspect this is the cause of #155.

If you considered maintaining this plugin in open source, I'd be happy to contribute fixes for all of the above. As the plugin is not obfuscated and just a wrapper around a transformer, I hope that's a feasible option. As it stands, the new preview implementation in 9.4.0 is not usable for us.

**Comment by ZacSweers** [comment]
Another option, if open sourcing is not viable, would be to run a tool like this on your repo to help catch common Gradle plugin issues: https://github.com/autonomousapps/gradle-best-practices-plugin

**Comment by msft-cofitz** [comment]
Thanks for the detailed feedback on the preview! We will review including fixes for these items in a future release.

**Comment by jerrellmardis** [comment]
@msft-cofitz do you have any updates on progress you can share?
