### ISSUE TITLE
Build failure after upgrade to 9.7.0 and grade 8 

### ISSUE THREAD

**Issue by jumpbayern** [msintuneappsdk/ms-intune-app-sdk-android#171]
After upgrade to intune SDK 9.7. and gradle 8 i have compile failure.

My App build successfull without this plugin.

![Bildschirmfoto 2023-08-08 um 12 48 28](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/763366/ad91d5cf-986c-48fa-bf28-ec54b918387e)

Who can help me or tell me how I can correct the error?

**Comment by mcsimons** [comment]
Hello, thanks for the report. Please re-open this issue and use one the issue templates we have created, that way we have all the information necessary to help you. 
https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/new/choose
