### ISSUE TITLE
App crashes on started with ClassCastException: com.microsoft.intune.mam.client.content.MAMContext cannot be cast to android.app.Application

### ISSUE THREAD

**Issue by nevertheless1975** [msintuneappsdk/ms-intune-app-sdk-android#172]
# Intune Android App SDK [Gradle Build Plugin] Issue

## Questions to Ask Before Submission

1. Does your app compile and launch successfully without the Intune App SDK?

The application does compile with and without the SDK included. However, on startup the app is crashing right away with a ClassCastException. 

java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.ClassCastException: com.microsoft.intune.mam.client.content.MAMContext cannot be cast to android.app.Application

3. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?

Yes. Two ClassCastException issue found which both seem to be unrelated. 
 
5. Are you using the latest version of the [SDK and Plugin]?

Yes. The error starts with the latest SDK (9.7.0) included. 

## Summary

The app is crashing on startup with the following stack trace. 

` java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.StartupException: androidx.startup.StartupException: java.lang.ClassCastException: com.microsoft.intune.mam.client.content.MAMContext cannot be cast to android.app.Application
        at android.app.ActivityThread.installProvider(ActivityThread.java:8195)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7698)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7452)
        at android.app.ActivityThread.access$1600(ActivityThread.java:310)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2277)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:226)
        at android.os.Looper.loop(Looper.java:313)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1133)`

## Details

- **Intune Android App SDK Version:**

9.7.0

- **Gradle Version:**

7.4.2

- **Operating System (Mac, Linux, Windows) and Version:**

MacOS - 13.5 (22G74)

- **Android Studio Version:**

Android Studio Dolphin | 2021.3.1 Patch 1

## Logs

Before submitting, please attach the following:

- [ ] [Gradle build logs file.](#android-studio--gradle-logs)
- [ ] [Gradle Build Plugin `output\logs` as a zip file.](#gradle-build-plugin-report-logs)

### Android Studio / Gradle Logs

Please write the output of your Gradle build (with the `--debug` and `--stacktrace` options) to a file and attach it to this issue.

### Gradle Build Plugin Report Logs

Please [enable reporting] and share the resulting files at `output\logs` as a zip file.

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

Gradle: androidx.activity:activity:1.2.4@aar
Gradle: androidx.annotation:annotation:1.3.0
Gradle: androidx.annotation:annotation:1.5.0
Gradle: androidx.annotation:annotation-experimental:1.1.0@aar
Gradle: androidx.appcompat:appcompat:1.4.2@aar
Gradle: androidx.appcompat:appcompat-resources:1.4.2@aar
Gradle: androidx.arch.core:core-common:2.1.0
Gradle: androidx.arch.core:core-runtime:2.1.0@aar
Gradle: androidx.asynclayoutinflater:asynclayoutinflater:1.0.0@aar
Gradle: androidx.browser:browser:1.0.0@aar
Gradle: androidx.collection:collection:1.1.0
Gradle: androidx.concurrent:concurrent-futures:1.1.0
Gradle: androidx.constraintlayout:constraintlayout:1.1.3@aar
Gradle: androidx.constraintlayout:constraintlayout-solver:1.1.3
Gradle: androidx.coordinatorlayout:coordinatorlayout:1.0.0@aar
Gradle: androidx.core:core:1.7.0@aar
Gradle: androidx.core:core-ktx:1.3.2@aar
Gradle: androidx.core:core-splashscreen:1.0.0-rc01@aar
Gradle: androidx.cursoradapter:cursoradapter:1.0.0@aar
Gradle: androidx.customview:customview:1.0.0@aar
Gradle: androidx.documentfile:documentfile:1.0.0@aar
Gradle: androidx.drawerlayout:drawerlayout:1.0.0@aar
Gradle: androidx.fragment:fragment:1.3.6@aar
Gradle: androidx.interpolator:interpolator:1.0.0@aar
Gradle: androidx.legacy:legacy-support-core-ui:1.0.0@aar
Gradle: androidx.legacy:legacy-support-core-utils:1.0.0@aar
Gradle: androidx.legacy:legacy-support-v4:1.0.0@aar
Gradle: androidx.lifecycle:lifecycle-common:2.4.0
Gradle: androidx.lifecycle:lifecycle-common:2.4.1
Gradle: androidx.lifecycle:lifecycle-extensions:2.2.0@aar
Gradle: androidx.lifecycle:lifecycle-livedata:2.0.0@aar
Gradle: androidx.lifecycle:lifecycle-livedata:2.2.0@aar
Gradle: androidx.lifecycle:lifecycle-livedata-core:2.3.1@aar
Gradle: androidx.lifecycle:lifecycle-process:2.2.0@aar
Gradle: androidx.lifecycle:lifecycle-process:2.4.0@aar
Gradle: androidx.lifecycle:lifecycle-runtime:2.4.0@aar
Gradle: androidx.lifecycle:lifecycle-runtime:2.4.1@aar
Gradle: androidx.lifecycle:lifecycle-service:2.2.0@aar
Gradle: androidx.lifecycle:lifecycle-viewmodel:2.3.1@aar
Gradle: androidx.lifecycle:lifecycle-viewmodel-savedstate:2.3.1@aar
Gradle: androidx.loader:loader:1.0.0@aar
Gradle: androidx.localbroadcastmanager:localbroadcastmanager:1.1.0@aar
Gradle: androidx.media:media:1.0.0@aar
Gradle: androidx.print:print:1.0.0@aar
Gradle: androidx.savedstate:savedstate:1.1.0@aar
Gradle: androidx.slidingpanelayout:slidingpanelayout:1.0.0@aar
Gradle: androidx.startup:startup-runtime:1.0.0@aar
Gradle: androidx.swiperefreshlayout:swiperefreshlayout:1.0.0@aar
Gradle: androidx.vectordrawable:vectordrawable:1.1.0@aar
Gradle: androidx.vectordrawable:vectordrawable-animated:1.1.0@aar
Gradle: androidx.versionedparcelable:versionedparcelable:1.1.1@aar
Gradle: androidx.viewpager:viewpager:1.0.0@aar
Gradle: androidx.webkit:webkit:1.4.0@aar

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

Gradle: com.airbnb.android:lottie:4.2.1@aar
Gradle: com.android.volley:volley:1.2.1@aar
Gradle: com.fasterxml.jackson.core:jackson-annotations:2.8.0
Gradle: com.fasterxml.jackson.core:jackson-core:2.8.2
Gradle: com.fasterxml.jackson.core:jackson-databind:2.8.2
Gradle: com.github.stephenc.jcip:jcip-annotations:1.0-1
Gradle: com.github.tony19:logback-android:2.0.1@aar
Gradle: com.google.android.datatransport:transport-api:3.0.0@aar
Gradle: com.google.android.datatransport:transport-backend-cct:3.1.8@aar
Gradle: com.google.android.datatransport:transport-runtime:3.1.8@aar
Gradle: com.google.android.gms:play-services-base:18.0.1@aar
Gradle: com.google.android.gms:play-services-basement:18.1.0@aar
Gradle: com.google.android.gms:play-services-cloud-messaging:17.0.1@aar
Gradle: com.google.android.gms:play-services-location:19.0.1@aar
Gradle: com.google.android.gms:play-services-places-placereport:17.0.0@aar
Gradle: com.google.android.gms:play-services-stats:17.0.2@aar
Gradle: com.google.android.gms:play-services-tasks:18.0.2@aar
Gradle: com.google.code.findbugs:jsr305:3.0.1
Gradle: com.google.code.gson:gson:2.8.9
Gradle: com.google.dagger:dagger:2.39.1
Gradle: com.google.dagger:dagger-lint-aar:2.39.1@aar
Gradle: com.google.dagger:hilt-android:2.39.1@aar
Gradle: com.google.dagger:hilt-core:2.39.1
Gradle: com.google.errorprone:error_prone_annotations:2.9.0
Gradle: com.google.firebase:firebase-annotations:16.2.0
Gradle: com.google.firebase:firebase-common:20.3.1@aar
Gradle: com.google.firebase:firebase-components:17.1.0@aar
Gradle: com.google.firebase:firebase-datatransport:18.1.7@aar
Gradle: com.google.firebase:firebase-encoders:17.0.0
Gradle: com.google.firebase:firebase-encoders-json:18.0.0@aar
Gradle: com.google.firebase:firebase-encoders-proto:16.0.0
Gradle: com.google.firebase:firebase-iid-interop:17.1.0@aar
Gradle: com.google.firebase:firebase-installations:17.1.3@aar
Gradle: com.google.firebase:firebase-installations-interop:17.1.0@aar
Gradle: com.google.firebase:firebase-measurement-connector:19.0.0@aar
Gradle: com.google.firebase:firebase-messaging:23.2.1@aar
Gradle: com.google.guava:listenablefuture:1.0
Gradle: com.microsoft.identity.client:msal:4.1.0@aar
Gradle: com.microsoft.identity:common4j:6.0.0
Gradle: com.microsoft.identity:common:9.0.0@aar
Gradle: com.nimbusds:nimbus-jose-jwt:9.9
Gradle: com.squareup.okhttp3:okhttp:3.12.13
Gradle: com.squareup.okio:okio:1.15.0
Gradle: com.squareup.okio:okio:1.17.4
Gradle: com.transistorsoft:tsbackgroundfetch:0.5.6@aar
Gradle: com.transistorsoft:tslocationmanager:3.2.10@aar
Gradle: cz.msebera.android:httpclient:4.5.8
Gradle: io.github.nishkarsh:android-permissions:2.1.6@aar
Gradle: io.jsonwebtoken:jjwt:0.7.0
Gradle: javax.inject:javax.inject:1
Gradle: me.leolin:ShortcutBadger:1.1.22@aar
Gradle: no.nordicsemi.android.support.v18:scanner:1.4.3@aar
Gradle: no.nordicsemi.android:ble:2.1.1@aar
Gradle: org.altbeacon:android-beacon-library:2.19.4@aar
Gradle: org.greenrobot:eventbus:3.3.1@aar
Gradle: org.greenrobot:eventbus-java:3.3.1
Gradle: org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.6.21
Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.6.21
Gradle: org.jetbrains.kotlin:kotlin-stdlib:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21
Gradle: org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10
Gradle: org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.6.21
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-android:1.4.2
Gradle: org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.4.2
Gradle: org.jetbrains:annotations:13.0
Gradle: org.parceler:parceler-api:1.1.12
Gradle: org.slf4j:slf4j-api:1.7.36

[Gradle Build Plugin]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#gradle-build-plugin
[enable reporting]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#reporting
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK and Plugin]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by nevertheless1975** [comment]
I guess I found the root cause.

**Comment by leoslima1** [comment]
@nevertheless1975 what's the root cause? I'm dealing with the same issue

**Comment by nevertheless1975** [comment]
@leoslima1 our app is using a subclass of android.app.Application which needs to be referenced in the android:name attribute of the application tag in the Android manifest file. That one got lost due to a change on our build process. Per default com.microsoft.intune.mam.client.content.MAMContext will be used which was causing the class cast exception. Adding this attribute again resolved the issue. 

https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase3#setting-mamapplication
