### ISSUE TITLE
Enrollment behavior when no policies are applied is different as compared to iOS

### ISSUE THREAD

**Issue by parveen-bhatia** [msintuneappsdk/ms-intune-app-sdk-android#173]
# Feature Request

## Questions to Ask Before Submission
Using Intune MAM SDK version: 9.5.0

## Summary
Scenario: No Intune MAM protection policies are configured. No Intune MAM app config policies are configured.
So, there are no policies configured. Even then Enrollment result is successful from Intune SDK>

## Reason For Request

In this scenario, on iOS enrollment fails. For iOS enrollment to work, either app config or protection or both policies must be applied. But this behavior is different in Android.

Please let us know whether it is bug or working as per design with different behavior on iOS and Android.
And why the behavior is different if it is working as designed.

**Comment by bannus** [comment]
@parveen-bhatia can you provide more details on the difference between the two platforms? What is the value of `IntuneMAMEnrollmentStatus` on iOS, and what is the value of `MAMEnrollmentManager.Result` on Android?

**Comment by parveen-bhatia** [comment]
@bannus On iOS, enrollment fails  statusCode: IntuneMAMEnrollmentStatusLicensedNotTargeted = 225**. On Android, enrollment is successful with result: **ENROLLMENT_SUCCEEDED**

**Comment by bannus** [comment]
Thanks for the info, we will investigate.

###### Internal tracking #25220901

**Comment by bannus** [comment]
We've determined this is working by design on Android. If the behavior on iOS is causing any issues/challenges for your app, please open a new ticket at https://github.com/msintuneappsdk/ms-intune-app-sdk-ios.

**Comment by parveen-bhatia** [comment]
> We've determined this is working by design on Android. If the behavior on iOS is causing any issues/challenges for your app, please open a new ticket at https://github.com/msintuneappsdk/ms-intune-app-sdk-ios.

Thanks for reverting. So, does it mean it is issue on iOS or does it mean it is designed differently on different platforms ?

**Comment by bannus** [comment]
@parveen-bhatia designed differently on different platforms.
