### ISSUE TITLE
[.NET MAUI] Microsoft.Intune.Maui.Essentials.Android Mamification failed: cannot find file class

### ISSUE THREAD

**Issue by ihariza** [msintuneappsdk/ms-intune-app-sdk-android#175]
# Intune Android App SDK for .NET MAUI
Mamification fails when build the project

## Summary

When you build the project, the task "MamifyFiles" throws a RuntimeException with the message " cannot find myapp.droid.Views.Hamburguer.HamburguerFragment: MyApp.Droid.Views.Hamburguer.HamburguerFragment found in myapp/droid/Views/Hamburguer/HamburguerFragment.class", but I can find the file in this path.

## Details

- **`Microsoft.Intune.Maui.Essentials.android Version: 9.5.2-beta2
- **Operating System (Mac, Linux, Windows) and Version: Windows 11
- **Visual Studio Version: 17.7.1

## Logs

7>Target _CompileJava:
7>  Building target "_CompileJava" completely.
7>  Output file "obj\Debug\net7.0-android\stamp\_CompileJava.stamp" does not exist.
7>  Task "RemoveDirFixed"
7>    Directory did not exist: E:\MyApp\MyApp.Droid.NET\obj\Debug\net7.0-android\android\bin\classes\
7>      RemovedDirectories:
7>  Done executing task "RemoveDirFixed".
7>  Task "Delete"
7>    File "obj\Debug\net7.0-android\android\bin\classes.zip" doesn't exist. Skipping.
7>  Done executing task "Delete".
7>  Using "Javac" task from assembly "C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.68\tools\Xamarin.Android.Build.Tasks.dll".
7>  Task "Javac"
7>    C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin\javac.exe -J-Dfile.encoding=UTF8 "@C:\Users\ihari\AppData\Local\Temp\tmp505B.tmp" -target 1.8 -source 1.8
7>    Note: Some input files use or override a deprecated API.
7>    Note: Recompile with -Xlint:deprecation for details.
7>    Note: Some input files use unchecked or unsafe operations.
7>    Note: Recompile with -Xlint:unchecked for details.
7>  Done executing task "Javac".
7>  Task "Touch"
7>    Creating "obj\Debug\net7.0-android\stamp\_CompileJava.stamp" because "AlwaysCreate" was specified.
7>    Touching "obj\Debug\net7.0-android\stamp\_CompileJava.stamp".
7>  Done executing task "Touch".
7>Target "_IntuneCompileClasspathReferences" skipped. Previously built successfully.
7>Target "_IntunePrepareJavaLibraries" skipped. Previously built successfully.
7>Target "_IntunePrepareLibraryProjectJars" skipped. Previously built successfully.
7>Target _IntuneMamifyJava:
7>  Building target "_IntuneMamifyJava" completely.
7>  Output file "obj\Debug\net7.0-android\stamp\_MamifyJava.stamp" does not exist.
7>  Task "MamifyFiles"
7>    Beginning mamification via the Build Tool CLI.
7>    Preparing intermediate directories for the Build Tool CLI...
7>    Intermediate output locations for Intune successfully created.
7>    Preparing arguments for the Build Tool CLI...
7>    Initializing the input file...
7>    Input file successfully initialized.
7>    Initializing the output file...
7>    Output file successfully initialized.
7>    Writing the input and output files...
7>    Input and output files written to E:\MyApp\MyApp.Droid.NET\obj\Debug\net7.0-android\intune\build-tool\.
7>    Passing arguments to the Build Tool CLI...
7>    Running command:
7>      Command: C:\Users\myUser\.nuget\packages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\BuildTool\bin\BuildToolCLI.bat
7>      Arguments: --input E:\MyApp\MyApp.Droid.NET\obj\Debug\net7.0-android\intune\build-tool\input.txt --output E:\MyApp\MyApp.Droid.NET\obj\Debug\net7.0-android\intune\build-tool\output.txt --excludeClasses mono.MonoRuntimeProvider;androidx.startup.InitializationProvider --classpath "C:\Program Files (x86)\Android\android-sdk\platforms\android-33\android.jar;C:\Users\myUser\.nuget\packages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Resources\classes.jar" --report E:\MyApp\MyApp.Droid.NET\obj\Debug\net7.0-android\intune\build-tool\report\ --xamarin
7>    Adding classpath C:\Users\myUser\.nuget\packages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Resources\classes.jar
7>    Adding classpath C:\Program Files (x86)\Android\android-sdk\platforms\android-33\android.jar
7>    Excluding androidx.startup.InitializationProvider
7>    Auto-excluding META-INF.versions.9.module-info
7>    Auto-excluding META-INF.versions.9.module-info
7>    Auto-excluding META-INF.versions.9.module-info
7>    Auto-excluding META-INF.versions.9.module-info
7>    Auto-excluding META-INF.versions.9.module-info
7>    Auto-excluding META-INF.versions.9.module-info
7>    Mamification failed: cannot find myapp.droid.Views.Hamburguer.HamburguerFragment: MyApp.Droid.Views.Hamburguer.HamburguerFragment found in myapp/droid/Views/Hamburguer/HamburguerFragment.class
7>    java.lang.RuntimeException: cannot find myapp.droid.Views.Hamburguer.HamburguerFragment: MyApp.Droid.Views.Hamburguer.HamburguerFragment found in myapp/droid/Views/Hamburguer/HamburguerFragment.class
7>    	at javassist.CtClassType.getClassFile3(CtClassType.java:213)
7>    	at javassist.CtClassType.getClassFile2(CtClassType.java:178)
7>    	at javassist.CtClassType.getDeclaringClass(CtClassType.java:864)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.isClassExcluded(BuildTimeMamifier.java:339)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.isClassExcluded(BuildTimeMamifier.java:313)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.setupEnclosedClasses(BuildTimeMamifier.java:257)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:192)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:107)
7>    	at com.microsoft.intune.mam.cli.MamifierMain.mainInternal(MamifierMain.java:96)
7>    	at com.microsoft.intune.mam.cli.MamifierMain.main(MamifierMain.java:49)
7>
7>    Exception in thread "main" java.lang.RuntimeException: cannot find myapp.droid.Views.Hamburguer.HamburguerFragment: MyApp.Droid.Views.Hamburguer.HamburguerFragment found in myapp/droid/Views/Hamburguer/HamburguerFragment.class
7>    	at javassist.CtClassType.getClassFile3(CtClassType.java:213)
7>    	at javassist.CtClassType.getClassFile2(CtClassType.java:178)
7>    	at javassist.CtClassType.getDeclaringClass(CtClassType.java:864)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.isClassExcluded(BuildTimeMamifier.java:339)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.isClassExcluded(BuildTimeMamifier.java:313)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.setupEnclosedClasses(BuildTimeMamifier.java:257)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.mamifyClasses(BuildTimeMamifier.java:192)
7>    	at com.microsoft.intune.mam.BuildTimeMamifier.mamify(BuildTimeMamifier.java:107)
7>    	at com.microsoft.intune.mam.cli.MamifierMain.mainInternal(MamifierMain.java:96)
7>    	at com.microsoft.intune.mam.cli.MamifierMain.main(MamifierMain.java:49)
7>    C:\Users\myUser\.nuget\packages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(238,9): error : The MAM transofrmation failed unexpectedly, please review the verbose logs for more details.
7>  Done executing task "MamifyFiles" -- FAILED.
7>Done building target "_IntuneMamifyJava" in project "MyApp.Droid.NET.csproj" -- FAILED.

## Questions to Ask Before Submission
1. Does the app build and launch without including the Microsoft.Intune.Maui.Essentials.android package? Yes
2. Does the issue reproduce if you rebuild after deleting the bin and obj output folders? Yes
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? Yes
4. Are you using the latest Microsoft.Intune.Maui.Essentials.android NuGet package version? Yes

**Comment by ihariza** [comment]
Is there any way to exclude files from the mamification process?

**Comment by ihariza** [comment]
This issue it's happening when I add the Xamarin tag [Register()] to an activity or fragment.

**Comment by MikeP0911** [comment]
@Archit-Pikle @ihariza 
I too get an error "MAM Transformation failed unexpectadly".
https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/182

**Comment by Archit-Pikle** [comment]
Hi @ihariza, I see there's a case difference in the fragment name in the logs you provided.

`7> Mamification failed: cannot find myapp.droid.Views.Hamburguer.HamburguerFragment: MyApp.Droid.Views.Hamburguer.HamburguerFragment found in myapp/droid/Views/Hamburguer/HamburguerFragment.class
`

Can you please fix the case and let me know if that fixes the issue?
If that doesn't work, can you provide a sample app that reproduces this issue?
