### ISSUE TITLE
[.NET MAUI] Microsoft.Intune.Maui.Essentials.Android Tries to run targets on non-android TargetFrameworks

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/ms-intune-app-sdk-android#176]
# Intune Android App SDK for .NET MAUI Issue

## Summary

Created a new MAUI project and installed the Microsoft.Intune.Maui.Essentials.android version 9.5.2 Beta. 
Immediately it throws 

Intune integration requires .Net 7.0. Please upgrade your app's target framework version.	MyMaui	C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets	

## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:** 9.5.2 Beta
- **Operating System (Mac, Linux, Windows) and Version**: Windows 11
- **Visual Studio Version**: 17.7.2

## Logs

1>C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(131,9): error : Intune integration requires .Net 7.0. Please upgrade your app's target framework version.
1>Done building project "MyMaui.csproj" -- FAILED.

1. Does the app build and launch without including the `Microsoft.Intune.Maui.Essentials.android` package? **Yes**
2. Does the issue reproduce if you rebuild after deleting the `bin` and `obj` output folders?**Yes**
3. Have you checked the [.NET MAUI repository](https://github.com/dotnet/maui/issues) for similar issues? If so, please follow the guidance there or add that information to this issue. **Not Available**
4. Are you using the latest `Microsoft.Intune.Maui.Essentials.android` NuGet package version? **Yes**

**Comment by MikeP0911** [comment]
To Reproduce
Steps to reproduce the behavior:

1. Using visual studio for mac 17.7.2
2. Create a new .NET MAUI App or an Android Application
3. Add Microsoft.Intune.Maui.Essentials.Android nuget package
4. Try to build the project
5. The build fails with the following message

1>C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(131,9): error : Intune integration requires .Net 7.0. Please upgrade your app's target framework version.
1>Done building project "MyMaui.csproj" -- FAILED.

**Comment by Archit-Pikle** [comment]
Hi @MikeP0911, Microsoft.Intune.Maui.Essentials.android requires the MAUI app to have a target framework of .NET 7.0.
Can you please confirm your MAUI app is targetting .NET 7?

**Comment by MikeP0911** [comment]
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-ios;net7.0-maccatalyst;net7.0-android33.0</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		
		
		<OutputType>Exe</OutputType>
		<RootNamespace>MyMaui</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		
		<ApplicationTitle>MyMaui</ApplicationTitle>

		
		<ApplicationId>com.companyname.mymaui</ApplicationId>
		<ApplicationIdGuid>91e8efcb-5f3a-4b44-a3be-d01168db3acd</ApplicationIdGuid>

		
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">29.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		
		<MauiFont Include="Resources\Fonts\*" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="Microsoft.Intune.Maui.Essentials.android" Version="9.5.2-beta2" />
	</ItemGroup>

</Project>

**Comment by MikeP0911** [comment]
@Archit-Pikle 
This is my csproj. Im not sure where im missing

**Comment by MikeP0911** [comment]
This is same like the problem mentioned below

https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/174

**Comment by Archit-Pikle** [comment]
Does it build if you replace “net7.0-android33.0” with “net7.0-android” in the target frameworks?

**Comment by MikeP0911** [comment]
@Archit-Pikle 

We have changed as per your advice. Still the problem exists.
Please suggest.
-------------------------------
Error:

Build started...
1>------ Build started: Project: MyMauiApp, Configuration: Debug Any CPU ------
Restored C:\Maui\MyMauiApp\MyMauiApp\MyMauiApp.csproj (in 400 ms).
1>C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(131,9): error : Intune integration requires .Net 7.0. Please upgrade your app's target framework version.
1>Done building project "MyMauiApp.csproj" -- FAILED.
1>C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(131,9): error : Intune integration requires .Net 7.0. Please upgrade your app's target framework version.
1>Done building project "MyMauiApp.csproj" -- FAILED.
1>C:\NugetPackages\microsoft.intune.maui.essentials.android\9.5.2-beta2\build\netstandard2.0\Microsoft.Intune.Maui.Essentials.android.targets(131,9): error : Intune integration requires .Net 7.0. Please upgrade your app's target framework version.
1>Done building project "MyMauiApp.csproj" -- FAILED.
1>MyMauiApp -> C:\Maui\MyMauiApp\MyMauiApp\bin\Debug\net7.0-android\MyMauiApp.dll
1>Zipping directory "C:\Maui\MyMauiApp\MyMauiApp\obj\Debug\net7.0-android\intune\android\bin\classes\" to "C:\Maui\MyMauiApp\MyMauiApp\obj\Debug\net7.0-android\intune\android\bin\classes.zip".
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build started at 10:43 AM and took 01:14.540 minutes ==========
-------


<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net7.0-android;net7.0-ios;net7.0-maccatalyst</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net7.0-windows10.0.19041.0</TargetFrameworks>
		
		
		<OutputType>Exe</OutputType>
		<RootNamespace>MyMauiApp</RootNamespace>
		<UseMaui>true</UseMaui>
		<SingleProject>true</SingleProject>
		<ImplicitUsings>enable</ImplicitUsings>

		
		<ApplicationTitle>MyMauiApp</ApplicationTitle>

		
		<ApplicationId>com.companyname.mymauiapp</ApplicationId>
		<ApplicationIdGuid>01211571-2772-48c8-bce0-9c15e333a294</ApplicationIdGuid>

		
		<ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
		<ApplicationVersion>1</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">11.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">13.1</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>
	</PropertyGroup>

	<ItemGroup>
		
		<MauiIcon Include="Resources\AppIcon\appicon.svg" ForegroundFile="Resources\AppIcon\appiconfg.svg" Color="#512BD4" />

		
		<MauiSplashScreen Include="Resources\Splash\splash.svg" Color="#512BD4" BaseSize="128,128" />

		
		<MauiImage Include="Resources\Images\*" />
		<MauiImage Update="Resources\Images\dotnet_bot.svg" BaseSize="168,208" />

		
		<MauiFont Include="Resources\Fonts\*" />

		
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
		<PackageReference Include="Microsoft.Intune.Maui.Essentials.android" Version="9.5.2-beta2" />
	</ItemGroup>

</Project>

**Comment by MikeP0911** [comment]
@Archit-Pikle 
Were you able to reproduce this issue in your side?

**Comment by Archit-Pikle** [comment]
Hi @MikeP0911 , I was able to reproduce the issue.
We'll be working on a fix and ship it in a future release.

In the meanwhile, can you instead add the following code and let me know if that resolves your issue?
This code should import the `Microsoft.Intune.Maui.Essentials.android` package only for Android builds
`  <ItemGroup Condition=" '$(TargetPlatformIdentifier)' == 'Android' ">
    <PackageReference Include="Microsoft.Intune.Maui.Essentials.android" Version="9.5.2-beta2"/>
  </ItemGroup>
`

**Comment by MikeP0911** [comment]
@Archit-Pikle 

Thank you for the confirmation.
Th condition did not change even after  it is imported in android builds alone.

Is the Xamain support ending by May 2024?
 Still there are issues in the intune packages and migrating the apps before the deadline would be a great challenge I think.

**Comment by MikeP0911** [comment]
@Archit-Pikle 
I was able to successfully build if I could target for Android builds. 
Is there a way to download nuget packages only for the particular platform.
If we install a nuget package from Nuget package manager it gets installed in all the platforms.
Thank you.

**Comment by MikeP0911** [comment]
@Archit-Pikle 
Im getting an error in MAM transformation of files.
Please have a look.
https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/182

I this related due to the workaround.

Thanks

**Comment by Archit-Pikle** [comment]
The fix should be available in our latest release 10.0.0-beta2.

With this release, you no longer need to specify the `TargetPlatformIdentifier` while importing `Microsoft.Intune.MAUI.Essentials.android`
