### ISSUE TITLE
[.NET MAUI] MAUI application throws error when microsoft.intune.maui.essentials.android package is installed.

### ISSUE THREAD

**Issue by NiladriPadhy** [msintuneappsdk/ms-intune-app-sdk-android#183]
# Intune Android App SDK for .NET MAUI Issue
When installed the Microsoft.Intune.Maui.Essentials.android beta package through command line prompt, received an error.
## Summary
Microsoft.Intune.Maui.Essentials.android link
https://www.nuget.org/packages/Microsoft.Intune.Maui.Essentials.android/9.5.2-beta#readme-body-tab

Error
/Users/niladri/.nuget/packages/microsoft.intune.maui.essentials.android/9.5.2-beta2/build/netstandard2.0/Microsoft.Intune.Maui.Essentials.android.targets(13,13): Error MSB4184: The expression "[MSBuild]::VersionLessThanOrEquals('', 33.0.26)" cannot be evaluated. Version string was not in a correct format. (MSB4184) (com.microsoft.rightsmanagement.mobile.viewer.android)

Further technical details
VS Mac 2022 17.6.4 (build 472)
Android Target Version 13

**Comment by rygo-msft** [comment]
Hi @NiladriPadhy, we need more information in order to investigate this further. Please create a new issue and provide this information requested by the MAUI issue template
