### ISSUE TITLE
Integration with Intune SDK default client

### ISSUE THREAD

**Issue by telipskiy** [msintuneappsdk/ms-intune-app-sdk-android#193]
I am trying to implement Intune support for our Android app. We have already successfully implemented Intune support for our iOS app. Based on our app architecture we have our own login and don't use MSAL for user's login. 

In the iOS case (using Intune SDK for iOS) after successful user login into the system if the user settings contain "mamManaged" flag we are using loginAndEnrollAccount method from IntuneMAMEnrollmentManager and it works fine. We don't need to link/interact with MSAL library, specify any MS app registration details like clientID, redirect URLs, etc.

But based on Intune SDK for Android docs, it seems for Android platform it is implemented by the other way. We should use MSAL for user login and after use this account for MAM registration. MSAL SDK for Android has PublicClientApplication class for getting MS token and "create" methods there require auth_config.json file with app MS app registration details. Based on our architecture and business needs we cannot create app registration for this (only for Intune login). Digging the docs we found (https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional):

> "If your app is using its own custom Azure Active Directory (AAD) settings for authentication, then the following steps should be taken for both public store apps, as well as internal LOB apps. The steps do not need to be taken if your app is using the Intune SDK default client ID."

We want to use Intune SDK default client ID for our Android app integration (the same as it works by default for iOS), but we cannot find any info about default clientID, redirect URL, etc., that should be specified in auth_config.json.

It is not sensitive data, but we cannot find any information about  Intune SDK default client to use with Intune Android SDK. Please, provide info on how we can use the default Intune client.

**Comment by boyzhang-msft** [comment]
Hi @telipskiy , thanks for providing this context. And in the integration process, iOS and Android differ quite a bit. Please review our doc on [Android developer guide](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1), specifically [this section regarding MSAL](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase1#should-my-application-integrate-the-microsoft-authentication-library-msal).

Let us know if our doc is not being clear on this part.

**Comment by telipskiy** [comment]
Thank you for provided feedback
