### ISSUE TITLE
[.NET MAUI] Sample Application using Latest Android Intune

### ISSUE THREAD

**Issue by MikeP0911** [msintuneappsdk/ms-intune-app-sdk-android#194]
# Intune Android App SDK for .NET MAUI Issue

## Summary

I couldnt find any Sample application using the latest Microsoft.Intune.Maui.Essentials.android version in .NET MAUI.
Could you please provide any sample application for reference.
When trying with the latest version the app crashes on the launch.

## Details

- **`Microsoft.Intune.Maui.Essentials.android` Version:** Latest
- **Operating System (Mac, Linux, Windows) and Version**:
- **Visual Studio Version**:

**Comment by Archit-Pikle** [comment]
Hi @MikeP0911 you can find a sample MAUI app at https://github.com/msintuneappsdk/ms-intune-app-sdk-android-samples
