### ISSUE TITLE
Getting "you can't get there from here" error 

### ISSUE THREAD

**Issue by rashidkhan2487** [msintuneappsdk/ms-intune-app-sdk-android#195]
# Intune Android App SDK Policy Enforcement Issue

## Questions to Ask Before Submission

1. Have you completed the exit criteria for each phase in the [Intune App SDK for Android Integration Guide]? Yes
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues? Yes
3. Are you using the latest version of the [SDK]? Yes

## Summary

When applied the conditional access to the app in azure, and when trying to login via android app getting this error.

![Error](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/19781781/a93d47f4-5be1-4a68-9dc6-82c19b66f464)

Each phase of the [Intune App SDK for Android Integration Guide] outlines specific exit criteria for proceeding to subsequent phases.

Please reference the specific exit criteria scenario that is failing.

## Repro Steps

Please provide concrete steps to reproduce the issue you are encountering.

1. Created a tenant in Azure
2. Assign conditional access to all the user. 
<img width="866" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/19781781/a869d7f8-bdf9-4a23-ab14-00758e3a1aae">

3. Doesn't assign approve browser to user and getting the above error. 
we don't want to assign all the user to have Edge browser as approved app. 

**Expectation:**

**Observation:**

## Details

- **Intune Android App SDK Version:**
- **Android Device Make and Model:**
- **Android Device OS Version:**
- **Android Studio Version:**

### Company Portal Logs

**Incident ID:**

For guidance, see [Report a problem in Company Portal or Intune app for Android].

### Screenshots and Recordings

If screenshots and/or recordings would help explain the behavior, please include them here.

## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

- NA

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

[Intune App SDK for Android Integration Guide]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase1
[Report a problem in Company Portal or Intune app for Android]: https://learn.microsoft.com/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by boyzhang-msft** [comment]
Hi @rashidkhan2487 , thanks for reaching out. Could you please fill in the needed information on this bug template? More specifically, the repro steps including the [Conditional Access policy details](https://learn.microsoft.com/en-us/entra/identity/conditional-access/howto-policy-approved-app-or-app-protection#require-approved-client-apps-or-app-protection-policy-with-mobile-devices), and the Company Portal Logs?

**Comment by rashidkhan2487** [comment]
@boyzhang-msft  I am not sure how to get the company portal log. But I updated the repro step

**Comment by mcsimons** [comment]
@rashidkhan2487 thank you, I will take a look at the added steps. Here is some documentation on getting company portal logs, after clicking "send logs" please reply here with the given incident ID - https://learn.microsoft.com/en-us/mem/intune/user-help/send-logs-to-your-it-admin-by-email-android#send-logs-from-company-portal

**Comment by mcsimons** [comment]
As was asked above, could you include the details of what policies you are setting when you are creating the conditional access policy? All I see above is a screenshot of our documentation. 
Double checking as well, have you successfully gone through the section of our integration guide to support Conditional Access? and completed that sections exit criteria? https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase7#support-app-protection-ca

**Comment by rashidkhan2487** [comment]
@mcsimons attached is the log that I fetched from my device. I applied "Required Approved Client app" policy for the users. 
[Log.zip](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/13503106/Log.zip)

I am double checking the exit criteria will update on that soon

**Comment by c-demello** [comment]
@rashidkhan2487 Please note that to support the Conditional Access grant “require app protection policy’ there is some work needed to be completed by the app. Has the team done the work to handle this scenario? Here’s the basic info:
i.	The following are the key requirements from apps to support App Protection CA.
1.	Integrate the Intune SDK
2.	Use MSAL SDK for all authentication flows with Azure Active Directory. There is a requirement to use the MSAL library to connect to the resource that’s protected by conditional access (for the “require app protection policy” grant)
3.	Follow the development documents for managing error conditions for the app enrollment flow
a.	[Android documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fdeveloper%2Fapp-sdk-android%23app-protection-ca&data=04%7C01%7Ccdemello%40microsoft.com%7C5f3db4bb3e0f485d61fc08d9f0c41433%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637805547216399773%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=bLeuRVhKHs8kCioeC0JdWiXe2SZeU00rZ4axFBeePGU%3D&reserved=0)
b.	[iOS documentation](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fdeveloper%2Fapp-sdk-ios%23app-protection-ca-support-optional&data=04%7C01%7Ccdemello%40microsoft.com%7C5f3db4bb3e0f485d61fc08d9f0c41433%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637805547216449770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JZhpjnxHvVHD9DZZ%2BKzEaSCZCqR%2BCSuS7QEyIAw%2BNsQ%3D&reserved=0)
There are a few key things in the instructions linked above.
a)	Your app needs to declare that it supports this CA grant.  Specific [details here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fmem%2Fintune%2Fdeveloper%2Fapp-sdk-android%23declaring-support-for-app-ca&data=04%7C01%7Ccdemello%40microsoft.com%7C5f3db4bb3e0f485d61fc08d9f0c41433%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637805547216449770%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O7Mcol0ARyTO3LGmkmfKArgE2ysliQqCSMKvOGeEg%2Bc%3D&reserved=0)
b)	Once you’ve declared your support you will start to get an error message back, when you receive this, you’ll call a remediate API in our SDK.  This is all outlined in the documentation above.

**Comment by mcsimons** [comment]
Closing this issue out due to inactivity. If there are still issues after following the steps provided by c-demello above, please open a new issue. Thanks.
