### ISSUE TITLE
ANR/Crash occurs when create WebView on Samsung One UI 6.0, Android 14

### ISSUE THREAD

**Issue by fegiowong1988** [msintuneappsdk/ms-intune-app-sdk-android#199]
# Feature Request

## Questions to Ask Before Submission

1. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for a similar feature request?
2. Are you using the latest version of the [SDK and Plugin](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases)?

## Summary

Please briefly describe the feature you are requesting.

## Reason For Request

Please indicate your reasoning for requesting this feature.

**Comment by rygo-msft** [comment]
We cannot investigate issues without the appropriate information.
@fegiowong1988 please refile this issue using the "Bug Report" issue template and provide the requested details
