### ISSUE TITLE
Unable to read App configuration , configuration key values

### ISSUE THREAD

**Issue by frpaf** [msintuneappsdk/ms-intune-app-sdk-android#201]
# Intune Android App SDK Policy Enforcement Issue

## Questions to Ask Before Submission

1. Have you completed the exit criteria for each phase in the [Intune App SDK for Android Integration Guide]?
      Yes, There is a working copy of the intune sdk in the play store with an app config trying to read a key value from the app config.
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?
      Yes, Could not find any issues similar
4. Are you using the latest version of the [SDK]?
     Yes. Downloaded from the ms intune sdk

## Summary

Each phase of the [Intune App SDK for Android Integration Guide] outlines specific exit criteria for proceeding to subsequent phases.

Please reference the specific exit criteria scenario that is failing.

## Repro Steps
**A copy of the source project with the issue is available at** 
`https://github.com/franferns/intune-app`

Please provide concrete steps to reproduce the issue you are encountering.

1. Integrating the intune sdk creating a folder in the app folder with MAMSDK with 
<img width="400" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/34622575-bd75-41c8-8427-76b39ee0fa9e" />

2. Making changes to the root build.gradle file 
<img width="988" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/de4c4baa-9459-4423-8e99-8706d5bfd4c3" />

3. Making changes to app/build.gradle file adding reference to the sdk aar file
<img width="1053" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/42b1a3a2-7fa8-40ea-8be0-16a4af10d2f6" />

and the settings.gradle file.

<img width="524" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/68a16e51-2b77-431f-a0d9-04167ed65d5f">

4. And then the code for accessing the config from the 
<img width="821" alt="image" src="https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/7d4356a9-f146-402b-a367-12180df2d30a">

5. The app configuration policy configured is as follows
![image](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/assets/129268891/5492bf69-e3bf-4636-958e-d3b91569395e)

**Expectation:**
To be able to read configured values app config policy "CustomerURL"
the value returned is null . Shown as a toast message.

**Observation:**
The code where we get an instance of the MAMAppConfig returns a object even on an non company portal device . Isnt it suppose to return null for no work profile (non company portal) related devices. 

## Details

- **Intune Android App SDK Version:** Latest (10.0.0)
- **Android Device Make and Model:** Samsung Galaxy S21 5G/Moto G 5G/ Few other phones too 
- **Android Device OS Version:** Android version 13 
- **Android Studio Version:** Android Studio Electric Eel | 2022.1.1 Patch 1
Build #AI-221.6008.13.2211.9514443, built on January 21, 2023
Runtime version: 11.0.15+0-b2043.56-8887301 aarch64
VM: OpenJDK 64-Bit Server VM macOS 14.1.1

**A copy of the source project with the issue is available at** 
`https://github.com/franferns/intune-app`

**Comment by bannus** [comment]
Please read the [exit criteria for the App Configuration section of our docs](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase6#exit-criteria). App configuration can be configured for [managed apps](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-managed-app) (as shown in your screenshots) or for [managed devices](https://learn.microsoft.com/en-us/mem/intune/apps/app-configuration-policies-use-android).

To receive managed app config, the user must be MAM-enrolled (see [MAM integration essentials](https://learn.microsoft.com/en-us/mem/intune/developer/app-sdk-android-phase4)).

To receive managed device config, the device must be enrolled (see [Enroll Android devices](https://learn.microsoft.com/en-us/mem/intune/fundamentals/deployment-guide-enrollment-android)).
