### ISSUE TITLE
Signout/Signin has cached credentials

### ISSUE THREAD

**Issue by bgore** [msintuneappsdk/ms-intune-app-sdk-android#204]
# Feature Request

## Questions to Ask Before Submission

1. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for a similar feature request?
Yes.
3. Are you using the latest version of the [SDK and Plugin](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases)?
Yes

## Summary

I've noticed on signout, that when our application unregisters and unenrolls an account with the Android SDK, account credentials appear to be saved in the Company Portal's webview.  When I sign back in, I enter the user's email address, but am no longer prompted for a password.  That seems to be cached and I immediately see the 'Get Access' screen, followed by a request for a PIN (which is part of the protection policy).

Is there some API I can call to clear the cache or prevent this from happening?

## Reason For Request

Please indicate your reasoning for requesting this feature.

**Comment by rygo-msft** [comment]
@bgore, the Intune SDK is not responsible for managing cached credentials. The [MSAL repo](https://github.com/AzureAD/microsoft-authentication-library-for-android) is the best place to start for support for authentication scenarios.
