### ISSUE TITLE
Upgrade from 9.1.0 to 10.0.0

### ISSUE THREAD

**Issue by TarekBenDriss** [msintuneappsdk/ms-intune-app-sdk-android#207]
# Intune Android App SDK [Gradle Build Plugin] Issue

## Questions to Ask Before Submission

1. Does your app compile and launch successfully without the Intune App SDK?
Yes
2. Have you checked the [Microsoft Intune App SDK for Android] repository for similar issues?
Yes
3. Are you using the latest version of the [SDK and Plugin]?
No

## Summary

Our app is using MAM sdk 9.1.0, and we want to update it to 10.0.0, but we can't find a documentation on how to update the library. We can only find the documentation of how to add the library to the project.
We tried removing the existing library and add it again using [this documentation](9.1.0) but it seems that it's an outdated docs since the option to import .jar/aar packages is no longer possible
## Details

- **Intune Android App SDK Version:**
9.1.0
- **Gradle Version:**
8.2
- **AGP Version:**
8.0.0-rc01
- **Operating System (Mac, Linux, Windows) and Version:**
Mac
- **Android Studio Version:**
Android Studio Hedgehog | 2023.1.1

## Logs

Before submitting, please attach the following:

NA

### Android Studio / Gradle Logs

Please write the output of your Gradle build (with the `--debug` and `--stacktrace` options) to a file and attach it to this issue.

NA
### Gradle Build Plugin Report Logs

Please [enable reporting] and share the resulting files at `output\logs` as a zip file.

NA
## AndroidX Dependencies

If your app includes any AndroidX libraries, please list them here, along with the version info:

- NA

## Third-Party Library Dependencies

If your app includes any third-party libraries, please list them here, along with the version info:

- NA

[Gradle Build Plugin]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#gradle-build-plugin
[enable reporting]: https://learn.microsoft.com/mem/intune/developer/app-sdk-android-phase3#reporting
[Microsoft Intune App SDK for Android]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android
[SDK and Plugin]: https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases

**Comment by mcsimons** [comment]
Hi @TarekBenDriss - we don't have specific documentation on how to upgrade the SDK version, you need to download the newest SDK and replace the old version you should not need to fully remove MAM when upgrading. We also have release notes with any noteworthy changes - https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/10.0.0.

**Comment by meghandaly** [comment]
Closing issue, please refer to @mcsimons response.
