### ISSUE TITLE
The policy managed apps didn't block copy/paste

### ISSUE THREAD

**Issue by Chenxi1123Tan** [msintuneappsdk/ms-intune-app-sdk-android#208]
In copy/paste protection config, we set 'Policy managed apps' as the restriction, which is supposed to block copy/paste from unmanaged apps to managed apps. however, in our testing we found that content copied from an unmanaged app can be pasted in the managed app.

**Comment by mcsimons** [comment]
Hi @Chenxi1123Tan - thanks for the report. Please re-open this issue with one of our provided templates. This way we will have all of the necessary information to investigate the issue you are seeing.
