### ISSUE TITLE
Exception in aquireTokenSilent. Need to do SSO login in android app.

### ISSUE THREAD

**Issue by pallavkumar112** [msintuneappsdk/ms-intune-app-sdk-android#21]
getting exception as 
/AuthManager: Exception : Request authority:https://login.microsoftonline.com/common clientid:d59c622f-c25f-4e01-bbd6-62446403b678 No result returned from acquireTokenSilent

I am using taskr Intune sample application for android to achieve SSO login using Company portal app but getting above exception. 

Thanks in Advance for your help. 
Please let me know if any code snippet is needed . Taskr sample application is available in below link : 
https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App

**Comment by joakley-msft** [comment]
This issue is over a year old and does not contain enough information for us to take direct action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring.
