### ISSUE TITLE
Issue with Conditional Access & Cross-app SSO - Error Code 53009

### ISSUE THREAD

**Issue by ACivilise** [msintuneappsdk/ms-intune-app-sdk-android#212]
Hi, 

We have been able to successfully run our application with Conditional Access and [Cross-app SSO on Android](https://learn.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on) for a majority of users. However, we're facing an issue with a subset of users who are unable to access the application.

Upon checking the sign-in logs in the Azure portal, we're seeing an error code 53009, stating: "Application needs to enforce Intune protection policies." Additional details provided are "MFA completed in Azure AD".

Within the "Authentication Details" tab, it shows that "MFA successfully completed". We've verified that the phones for these users are enrolled properly.

Interestingly, we've observed that once these users log in to Outlook, they regain access to our app.

This issue seems to be affecting only some users and we have been unable to identify a pattern or common factor among them. Any insights into why this specific behaviour is occurring would be very helpful.

**Comment by bannus** [comment]
Hi, this issue report has none of the details requested in our issue template. Please re-open a new issue using the issue template.
