### ISSUE TITLE
Is there any Intune SDK integrated Android app with SSO login sample app?

### ISSUE THREAD

**Issue by pallavkumar112** [msintuneappsdk/ms-intune-app-sdk-android#22]
Tried to create SSO login for Android app , following below url  : 
https://docs.microsoft.com/en-us/azure/active-directory/develop/scenario-mobile-app-registration

Now once i try to login , getting exception as : 
Authentication error : the base64 url encoded signature component of the redirect uri does not match the expected value.
Please find the screenshot for the same. 

Need help to make SSO login android app. please let me know if any sample app is there where Intune SDK is integrated and SSO login is enabled.
![Screenshot_20190529-003953](https://user-images.githubusercontent.com/51072934/58556846-96217580-823a-11e9-8b36-f78c07a79964.png)

Thanks for advance.

**Comment by heidijinxujia** [comment]
Please follow the instruction [here](https://github.com/AzureAD/azure-activedirectory-library-for-android#how-to-use-this-library).  
•	Developer needs to register special redirectUri for broker usage. RedirectUri is in the format of msauth://packagename/Base64UrlencodedSignature. **You can get your redirecturi for your app using the script GetBrokerRedirectURI.ps1 on Windows or brokerRedirectPrint.sh on Linux or Mac. You can also use API call mContext.getBrokerRedirectUri.** Signature is related to your signing certificates.

**Comment by msintuneappsdk** [comment]
Closing this issue since we have worked with the team offline.
