### ISSUE TITLE
Support for React Native

### ISSUE THREAD

**Issue by chaudharyDescendant** [msintuneappsdk/ms-intune-app-sdk-android#232]
Want to know if there is a support available for integrating intune in React-Native based PWA's 

## Questions to Ask Before Submission

1. Have you checked the [Microsoft Intune App SDK for Android](https://github.com/msintuneappsdk/ms-intune-app-sdk-android) repository for a similar feature request? Yes, https://github.com/msintuneappsdk/ms-intune-app-sdk-ios/issues/21
2. Are you using the latest version of the [SDK and Plugin](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases)? Yes

## Summary

I'm trying to integrate Intune into a React Native-based Progressive Web App. My web app is built using Next.js. I'm struggling to find any implementation guides or relevant sources for this integration. Any advice or resources would be greatly appreciated.

**Comment by ChismanRaheem** [comment]
HI @chaudharyDescendant Thank you for submitting this request, I will engage our product group with this feature enhancement request. No other actions are required on your side and this incident will be updated with a tracking number.

`Note currently, we do not provide support or guidance for apps other than our supported platform. `

**Comment by dgrover-spotnana** [comment]
Hey @ChismanRaheem  , any plans on supporting React Native in near future ?
