### ISSUE TITLE
Issue with SSO login with Intune SDK integrated native IOS and Android Apps

### ISSUE THREAD

**Issue by pallavmitianster** [msintuneappsdk/ms-intune-app-sdk-android#26]
Getting exception as
I/AuthManager: Exception : The base64 url encoded signature component of the redirect uri does not match the expected value. Type: com.microsoft.aad.adal.cl

Using Intune SDK and ADAL lib to build intune SDK integrated native Android app and It works fine if we login to app without SSO. 
Now Trying to implement SSO login as Microsoft document says in below link: 
https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-android
But it doesnt work and getting exception as above.

**I need solution urgently**, Please let me know if anyone can help or we can discuss about the **freelancing charges** if needed.

I can provide code snippet if required . I am using Taskr sample application as a test application which link given below :
https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App

**Comment by pallavmitianster** [comment]
tagging @msintuneappsdk @aanavath @oydang @aanavath @joakley-msft

**Comment by cofitz1** [comment]
Hi @pallavmitianster can you confirm that your redirect URI is configured correctly? https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-v1-enable-sso-android#step-2-establish-a-new-redirect-uri-with-your-url-scheme

**Comment by pallavmitianster** [comment]
Hi @cofitz1  yes ,I have followed the same link to configure redirect URI . Can you Please check and let me know i can provide all information needed.

Thanks

**Comment by cofitz1** [comment]
```
I/AuthManager: Exception : The base64 url encoded signature component of the redirect uri does not match the expected value. Type: com.microsoft.aad.adal.cl
```

It appears that your registered redirect URI does not match the one that is expected from the `msauth://packagename/Base64UrlencodedSignature` format.  Can you verify that you set this up correctly based on your app signature?

If this is not the error the [ADAL](https://github.com/AzureAD/azure-activedirectory-library-for-android#sso-and-conditional-access-support) team may be able to assist you further.
