### ISSUE TITLE
Difference in App Un-enrollment behavior in iOS and Android

### ISSUE THREAD

**Issue by AbhijitParate** [msintuneappsdk/ms-intune-app-sdk-android#27]
When un-enrolling the app by calling
```
MAMEnrollmentManager::unregisterAccountForMAM(String upn)
```
in iOS, method accepts additional flag 'withWipe' but in Android app's data gets wiped forcefully.

Is there any way we can get similar behavior as iOS?
We don't really want to wipe the app's data in Android.

**To Reproduce**
- Unenroll Android app by calling above method.
- Notice the crash (possibly due to force wipe of app data)

**Expected behavior:**
- App should not crash

**Intune App SDK for Android : **
- Intune SDK 6.0.0
- Java / Kotlin

**Comment by AbhijitParate** [comment]
@msintuneappsdk

**Comment by AbhijitParate** [comment]
Must register for MAMNotificationType.WIPE_USER_DATA notifications.

**Comment by ClaudioConsolmagno** [comment]
Thanks that was helpful, was having the same issue and couldn't figure out why until I came across this. Solution:
```java
MAMComponents.get(MAMNotificationReceiverRegistry.class).registerReceiver(logoutAndWipeData, MAMNotificationType.WIPE_USER_DATA);
```

Documentation link: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#types-of-notifications
