### ISSUE TITLE
Link to "Gradle Plugin Instructions" is dead

### ISSUE THREAD

**Issue by mukulhase** [msintuneappsdk/ms-intune-app-sdk-android#29]
**Describe the bug:**
Documentation issue: Link to "Gradle Plugin Instructions" is dead

**To Reproduce**
1. View Readme.md

**Expected behavior:**
Link shouldn't be dead.

**Comment by msintuneappsdk** [comment]
Hi @mukulhase,

Previously, we had the gradle plugin instructions in the GitHub repository *only* and not within our Intune Docs. This is the set of gradle plugin instructions you can refer to: https://docs.microsoft.com/en-us/intune/developer/app-sdk-android#gradle-build-plugin

We can edit the readme.md file to remove the dead link. Thanks for bringing it to our attention.
