### ISSUE TITLE
sample app to test Intune SDK functionality

### ISSUE THREAD

**Issue by Durgaprasad-Budhwani** [msintuneappsdk/ms-intune-app-sdk-android#3]
Hi team,
Can we get sample app to test Intune SDK functionality?

**Comment by billge** [comment]
+1

**Comment by maggix** [comment]
+1

**Comment by ThomasSHA** [comment]
+1

**Comment by TakatsuguHirata** [comment]
+1

**Comment by umarF** [comment]
Seriously this is a must !

**Comment by msintuneappsdk** [comment]
We have released a sample app for Android using the latest Intune SDK for Android plugin, here: https://github.com/msintuneappsdk/Resource-Requester
