### ISSUE TITLE
Gradle Sync Error when combining with Realm Latest Version

### ISSUE THREAD

**Issue by cabanasn** [msintuneappsdk/ms-intune-app-sdk-android#32]
**Describe the bug:**
I need to update the version of Realm DB to the latest because of a security vulnerability. When doing so, as soon as I try to sync the gradle plugin I get an error on **com.microsoft.intune.mam.MamifyConfiguration**

**Screenshots and logs:**
![Screen Shot 2019-12-16 at 12 22 21 PM](https://user-images.githubusercontent.com/7597858/70919001-c970f980-1ffe-11ea-8c6f-10435a83a643.png)
![Screen Shot 2019-12-16 at 12 22 28 PM](https://user-images.githubusercontent.com/7597858/70919002-c970f980-1ffe-11ea-836b-8717b393848e.png)

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
**Latest Version**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
**Android Studio using Kotlin**
- For errors during build, does the app build without Intune SDK integration?
**Yes**
- Who is the customer?
**CipherHealth LLC**

**Comment by cabanasn** [comment]
I think the problem is that the Realm library uses **javassist** v3.25.0-GA and the current mam gradle script crashes when setting that version. Are there any plans to support that version?

**Comment by EarlyWild** [comment]
I am having the same error.

**Comment by joakley-msft** [comment]
The Intune MAM gradle plugin has been updated to use Javassist 3.27
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin
