### ISSUE TITLE
Need login twice for Intune and internal APP

### ISSUE THREAD

**Issue by Sicmatr1x** [msintuneappsdk/ms-intune-app-sdk-android#33]
Hello, our company's APP is provided by Intune for internal employees of the company. After logging in through the Intune, download and install, but the employees report that they need to log in twice on the Intune and our internal used app during the use process. Ask if there are any login authorization schemes that can simplify this operation?
Login the Intune and our internal APP both used office365 account, and our authorization part used OAuth.

**Comment by msintuneappsdk** [comment]
Two questions.

  1.  What are the two logins?  Is the first to get MAM policy and the second to logging into your service?
  2.  Did you wrap your app or build in the SDK?

**Comment by Sicmatr1x** [comment]
The user workflow is:
1. Download Intune APP
2. Login into Intune
3. Download internal APP in Application
4. Open internal APP
5. Alert login page and title is microsoft(For one device if login in one internal APP, others will skip this step)
6. Login internal APP

For the step 2: when user write company's employee email will redirect to our organization login page

Yes, we use Wrapping Tool to wrap our internal APP

Questions:
1. Could skip step 5 be possible?
2. Does skip step 6 be possible? For example, take a token to our authorization server. If true, how to leverage the shared token to achieve the single sign-on.
3. Is wrap by wrapping tool and build in the SDK has the same function?
4. If need use Intune as internal App Store, could upload no wrap apk? or without SDK?

**Comment by msintuneappsdk** [comment]
Thanks for the info.  Right now, Intune is being called with a default AAD client ID in our wrapper.  You can change that to use your AAD client in the wrapper.  There are a couple of steps you need to do for this.

  1.  Update the AndroidManifest.XML before wrapping following these instructions<https://docs.microsoft.com/en-us/intune/developer/app-sdk-android#configure-azure-active-directory-authentication-library-adal>.
  2.  Make sure you give your app access to the Intune app protection service.  You’ll find these instructions here:  https://docs.microsoft.com/en-us/intune/developer/app-sdk-android#configure-azure-active-directory-authentication-library-adal

**Comment by joakley-msft** [comment]
No further activity since last Microsoft guidance 8 months ago, closing.
