### ISSUE TITLE
Can not enroll user untill app's storage is clear when policies are removed and added

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [msintuneappsdk/ms-intune-app-sdk-android#34]
**Describe the bug:**
Could not enroll the application when the policies are removed for the first time and added from the next time. We are able to enroll only after clearing the storage of application and trying enrollment.

**To Reproduce**
1. Remove the policies for the user in azure intune portal
2. Try enrolling app
3. You will get NOT_LICENSED, which is desired.
4. Now Add the policies for the user in intune portal.
5. Try enrolling in the app.
6. **Still you will get NOT_LICENSED**
7. Clear app storage, and try enrollment. Now it will enroll.

**Expected behavior:**
The enrollment should happen at 6th step with out clearing the app storage.

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
**6.0.0**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
**Java**

**Comment by shanmugpriyan306** [comment]
@chaitanya-vanapamala did you got it working?

Could you please if you have fix. I am facing similar NOT_LICENSED issue.

**Comment by joakley-msft** [comment]
This is expected: there is a 12-hour interval between rechecks for new policy. This is documented at https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-delivery.
