### ISSUE TITLE
Login Credentials are asked always to get MAM Policies.

### ISSUE THREAD

**Issue by chaitanya-vanapamala** [msintuneappsdk/ms-intune-app-sdk-android#36]
**Describe the bug:**
Azure Login credentials are being prompted always which acquiring token, when when Prompt behavior set to Auto.

**Steps to Reproduce**
1. Enroll the Application with MAM by login to Azure account.
2. Unenroll the user.
3. Try enroll again.

At step 3 in iOS app credentials are not asked with the same user who logged in at 1st step. This is different in Android.

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
Version 6.3.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
Java

**Comment by joakley-msft** [comment]
The Intune MAM SDK does not control or affect prompt behavior in the ADAL or MSAL SDKs, nor does it provide a mechanism to acquire tokens itself. If this issue still occurs, please report it to the relevant authentication SDK.
