### ISSUE TITLE
Is Intune SDK for Android support MSAL?

### ISSUE THREAD

**Issue by trifist** [msintuneappsdk/ms-intune-app-sdk-android#43]
Hi team,
I want to integrate Intune MAM functions to my apps and read the official documentation. It says that I have to integrate ADAL first to acquire tokens for Intune SDK. However, when I read the docs for ADAL, it told me not to use ADAL anymore, using MSAL instead. I'm a little confused about that, which one should I use? The samples here do use ADAL, should I follow that?
Sample: https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App

**Comment by msintuneappsdk** [comment]
We do support MSAL.  We have not updated our sample applications yet.

**Comment by Matthias-Hager** [comment]
Hi,
We are also working on integrating the Intune SDK to our app and want to know how to do this with MSAL. When can we expect the documentation and sample apps being available?

Regards Matthias Hager

**Comment by navjyot** [comment]
You can refer below document for MSAL.

https://docs.microsoft.com/en-us/azure/active-directory/develop/tutorial-v2-android

**Comment by staticvoid7** [comment]
[Taskr-Sample-Intune-Android-App](https://github.com/msintuneappsdk/Taskr-Sample-Intune-Android-App) has been updated and uses MSAL since version 2.0.

**Comment by meghandaly** [comment]
The SDK supports MSAL integration, for integration guidance see [Configure Microsoft Authentication Library (MSAL)](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#configure-microsoft-authentication-library-msal).
