### ISSUE TITLE
Cannot build library module using the gradle plugin

### ISSUE THREAD

**Issue by phs09010423** [msintuneappsdk/ms-intune-app-sdk-android#44]
**Describe the bug:**
I'm getting the following error when using mam plugin in library module

**To Reproduce**
1. make a sub module
2. add mam plugin in module gradle 
    plugins {
        id 'com.android.library'
        id 'com.microsoft.intune.mam'
    }

**Screenshots and logs:**
Error Log : Transforms with scopes '[SUB_PROJECTS]' cannot be applied to library projects.

**Intune App SDK for Android (please complete the following information):**
- Intune SDK Version : 6.6.1
- Android Studio 4.2 Canary 3
- Gradle version : 4.2.0-alpha03
- Gradle Wrpper : gradle-6.5-bin

**Comment by joakley-msft** [comment]
The MAM plugin is intended to be applied to your application module, not to a library module. When applied to the application module, libraries will still be processed, as documented at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#usage-of-includeexternallibraries
