### ISSUE TITLE
How to create Device Registration for LOB app

### ISSUE THREAD

**Issue by Innova133** [msintuneappsdk/ms-intune-app-sdk-android#48]
**Describe the bug:**
When we authenticate via MSAL and then register our LOB app for MAM enrollment ```enrollmentManager.registerAccountForMAM(...)```, we never get the screen that asks the user to register their device.

[Device Registration Screen](https://i.imgur.com/w3jSvC2.jpg)

We do see this screen when the user authenticates to Microsoft developed apps (ie, Outlook).

This is an issue because without the device record in the Intune Portal, there is no way to remotely wipe the LOB app data from a users device (for example if they lose the device).

**To Reproduce**
1. Authenticate the user (Single account) via MSAL
2. Register the Account for MAM
3. Device Registration Screen does not show up.

**Expected behavior:**
The device registration should show up.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: Pixel 4 XL
 - OS: Android 10

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using?  6.7.0 Are you using the latest version? Yes
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Native Android (Kotlin)
- For errors during build, does the app build without Intune SDK integration? No errors.
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? Employees
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**

**Comment by pavanbuzz** [comment]
Our application uses [Default enrollment](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#default-enrollment-optional). 
We experienced a scenario where the user does not have any of the Microsoft apps like Outlook or Teams. They installed our LOB app from Company portal. Our LOB app can successfully enroll the MAM user. However, when our applications uses MSAL to  acquire token, it fails stating `Device state: Unregistered`. 

And after we register the device using Outlook/Authenticator, when we retry acquiring token, it states `Application needs to enforce Intune protection policies.` with `Sign-in error code:	53009`. 

- Are there any SDK methods to call to start enforcing the policies?
- Is there any way for our application to invoke device registration like Microsoft app (Outlook) like this -

![image](https://user-images.githubusercontent.com/5876226/91534917-b2d4bd80-e955-11ea-9487-01bdd9594404.png)

**Comment by joakley-msft** [comment]
It sounds as though the resource you're trying to authenticate to uses APP CA. See the following for directions on how to use MAMComplianceManager to ensure that Intune MAM policies are in place https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-protection-ca

Please re-open if this does not resolve the issue.
