### ISSUE TITLE
android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference

### ISSUE THREAD

**Issue by maggix** [msintuneappsdk/ms-intune-app-sdk-android#5]
Hi, is there any working sample on this library? The iOS SDK was integrated just fine, but the Android SDK fails to get the Primary User. 
When calling this method:

```
MAMUserInfo info = MAMComponents.get(MAMUserInfo.class); if (info != null) return info.getPrimaryUser();
```

The error is:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.SharedPreferences android.content.Context.getSharedPreferences(java.lang.String, int)' on a null object reference
```

All components, libraries, etc. everything is set up according to the tutorial on Microsoft website https://docs.microsoft.com/en-us/intune/app-sdk-android

Thank you

**Comment by joakley-msft** [comment]
This issue is over a year old and does not contain enough information for us to take direct action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring.
