### ISSUE TITLE
MAMComponents.GetUserInfo().PrimaryUser; // Exception is thrown

### ISSUE THREAD

**Issue by ChristopheBernardAfelio** [msintuneappsdk/ms-intune-app-sdk-android#52]
Hello everyone,

We are developing an android native android app for one of our clients.
We had been using Intune SDK (with the gradle plugin) to get the connected user email ont their company phones (fully managed).

For android 10, our client have since decided to migrate from intune app provisioning to play store android enterprise deployment and this is when did not received the user any more.
The private playstore account is correctly linked to intune, users from our client can install the app from the play store so everything on that part is correctly setup.

We now have the following error (i'm copying Java code but our app is written in Kotlin);
**MAMComponents.GetUserInfo().PrimaryUser; // Exception is thrown**
Our bug has the same behavior as the one described here :
https://forums.xamarin.com/discussion/94217/microsoft-intune-mam-how-to-get-user-id-on-android

Note : if we inspect the code in debug just before the crash, we can see that the user is null indeed.

We are running android 10 on Samsung Galaxy A50 and A6 smartphones.
So far we have tested every release of the SDK from 6.0.0 to 7.0.0 with the same outcome.

We have also tested : 
- In both debug and release mode
- App in alpha, beta and release on google play store

We can see that the taskr sample uses MAMEnrollmentManager and ADAL.
It is not clear from the documentation that it is a required setup so we ignored it
(as it was already working just fine when we were deploying with intune directly).

Thanks for your help, any advice is welcome!
Kind regards,

Christophe

**Comment by joakley-msft** [comment]
This issue is nearly a year old and does not contain enough information for us to take direct action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring. We need to know specifically *what* exception is being thrown when you try to get the primary user.
