### ISSUE TITLE
Manifest merge build error with version 7.0

### ISSUE THREAD

**Issue by harikrishnagit** [msintuneappsdk/ms-intune-app-sdk-android#53]
**Describe the bug:**
Missing 'package' key attribute on element package at [:Microsoft.Intune.MAM.SDK] AndroidManifest.xml:19:9-77

**To Reproduce**
1. Follow Microsoft Intune App SDK for Android developer guide to integrate Referencing Intune App 

2. Add Microsoft.Intune.MAM.SDK.aar module
2. Add Module dependency
3. Gradle build 
4. Merge manifest throws "Missing 'package' key attribute on element package at [:Microsoft.Intune.MAM.SDK] AndroidManifest.xml:19"

**Expected behavior:**
The build to complete successfully. 

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: Android Studio 4
 - OS: MacOS

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Latest version 7.0.1
- What platform is your app based in React-Native
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? Department of Homeland Security (DHS)
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**
It appears that <queries> tag is used, this tag is introduced in Android 11. The app we are developing does not target Android 11.
<img width="728" alt="Screen Shot 2020-09-18 at 11 22 32 AM" src="https://user-images.githubusercontent.com/19350707/93615340-43288000-f9a1-11ea-9c63-c6f2675e674a.png">

**Comment by pavanbuzz** [comment]
Our project has the same issue with the latest version of SDK

**Comment by harikrishnagit** [comment]
I used version 6.7, and that solved the issue.

**Comment by weiyin** [comment]
I am also having this problem with the latest version 7.2.2.

**Comment by maphongba008** [comment]
Hi there, any solution or work around? I'm stuck with it for days

**Comment by maphongba008** [comment]
Upgrade to gradle 4.x solved this issue

**Comment by ianbby** [comment]
https://android-developers.googleblog.com/2020/07/preparing-your-build-for-package-visibility-in-android-11.html for future context

**Comment by joakley-msft** [comment]
Thank you, ianbby
