### ISSUE TITLE
Unable to access voice to text service with Intune SDK integrated

### ISSUE THREAD

**Issue by sumitsahoo** [msintuneappsdk/ms-intune-app-sdk-android#55]
**Describe the bug:**
We have an app which has Intune integrated and has ADAL libraries and it can not access any voice service. Is this a bug ? Once we remove `Microsoft.Intune.MAM.SDK.aar` it starts to work again. The project is in React Native but Intune is integrated natively. For voice input we are using `https://github.com/react-native-voice/voice` library.

```
//    implementation files('MAMSDK/Microsoft.Intune.MAM.SDK.aar')
//    implementation files('MAMSDK/Microsoft.Intune.MAM.SDK.Support.v4.jar')
//    implementation files('MAMSDK/Microsoft.Intune.MAM.SDK.Support.v7.jar')
//    implementation ("com.microsoft.aad:adal:3.1.0")
//            { exclude group: 'com.microsoft.device.display' }
```

**To Reproduce**
Integrate Tinune SDKs and voice input stops working.

**Expected behavior:**
Voice input should work without Intune libraries blocking the access.

**Screenshots and logs:**

Here is the logcat from Android Studio
```
2020-10-27 18:10:46.850 16651-16651/com.vodafone.intunes_poc I/ageManagerPolicyFactory: Disallowing access to package com.google.android.googlequicksearchbox
2020-10-27 18:10:46.850 16651-16651/com.vodafone.intunes_poc W/PolicyPackageManager: Disallowing access to service in system app com.google.android.googlequicksearchbox this may be undesired.
2020-10-27 18:10:46.851 16651-16651/com.vodafone.intunes_poc E/SpeechRecognizer: bind to recognition service failed
```

**Smartphone (please complete the following information):**
 - Device: OnePlus A5010
 - OS: Android 8.1.0

**Intune App SDK for Android (please complete the following information):**
- Intune SDK Version : `7.0.1`
- Platform :  `Java, JavaScript/ReactNative` ADAL and Intune integrated in native project directories as official React Native support is missing.
- For errors during build, does the app build without Intune SDK integration? `Yes`
- For errors post build, does the app launch without being Intune SDK integrated? `Yes`
- Who is the customer? `Vodafone Group`
- Do you see a trend with it only being reproduced on a specific device? `No`

**Additional context:**
NA

**Comment by joakley-msft** [comment]
This issue is nearly a year old and does not contain enough information for us to take action. We have instituted new practices for monitoring issues regularly. Please re-open if this is still occurring. If you do-reopen, please describe the voice input step in more detail. How is voice-input being initiated? Is it through the keyboard (in which case which keyboard are you using), or through something specific to your app? How does the failure manifest -- i.e. what error is shown?
