### ISSUE TITLE
File created in public storage is encrypted

### ISSUE THREAD

**Issue by staticvoid7** [msintuneappsdk/ms-intune-app-sdk-android#57]
We integrated the Android Intune SDK into our Android app. The Intune SDK version is 7.0.1.

The app protection policy value "Encrypt org data" is set to "Require". And the value "Encrypt org data on enrolled devices" is also set to "Require".

In our app we show a "save as" dialog using the [Android Storage Access Framework](https://developer.android.com/training/data-storage/shared/documents-files) in order to save a file:
```
// Request code for creating a PDF document.
private static final int CREATE_FILE = 1;

private void createFile() {
    Intent intent = new Intent(Intent.ACTION_CREATE_DOCUMENT);
    intent.addCategory(Intent.CATEGORY_OPENABLE);
    intent.setType("application/pdf");
    intent.putExtra(Intent.EXTRA_TITLE, "invoice.pdf");

    startActivityForResult(intent, CREATE_FILE);
}
```
After the user has selected a file using the system's file picker, we retrieve the selected URI in `onActivityResult()`. By getting a reference of the selected URI we can edit the file in place. We overwrite the contents of the file represented by the given URI.
```
@Override
public void onActivityResult(int requestCode, int resultCode, Intent resultData) {
    if (requestCode == CREATE_FILE && resultCode == Activity.RESULT_OK) {
        // The result data contains a URI for the document that the user selected.
        Uri uri = null;
        if (resultData != null) {
            uri = resultData.getData();
            // Perform operations on the document using its URI.
            writeFile(uri);
        }
    }
}

private void writeFile(Uri uri) {
    try {
        File source = new File("invoice.pdf");
        try (FileInputStream fileInputStream = new FileInputStream(source);
                OutputStream outputStream = getContentResolver().openOutputStream(uri, "w")) {
            copy(fileInputStream, outputStream);
        }
    } catch (IOException e) {
        //Error
    }
}

private void copy(InputStream is, OutputStream os) throws IOException {
    byte[] buffer = new byte[1024];
    int len;
    while ((len = is.read(buffer)) != -1) {
        os.write(buffer, 0, len);
    }
}
```
The app logs are:
```
com.microsoft.intune.mam.client.content.pm.PackageManagerPolicyFactory - Package is one of the Android local file provider packages: com.android.providers.downloads
com.microsoft.intune.mam.client.content.ContentManagementBase - Encrypting file created through ContentManagement
Cannot do atomic encryption change on /storage/emulated/0/Download/invoice.pdf
com.microsoft.intune.mam.Native - Cannot do atomic encryption change on -511988699
```
The created file is encrypted and cannot be opened by other apps. The expected behavior is that files saved in the public storage are unencrypted. And other apps should be able to open these files.

The error does not occur without the Intune SDK.

- Device: BlackBerry Motion BBD100-1
- OS: Android 8.1.0

**Comment by joakley-msft** [comment]
I'm afraid your understanding of the expected behavior is incorrect -- this is functioning as designed. The "Encrypt Org Data" setting leads to encryption of all files created by the app, including in public locations.
