### ISSUE TITLE
MS Intunes integration for React Native and client impact

### ISSUE THREAD

**Issue by jarnakantaria-gep** [msintuneappsdk/ms-intune-app-sdk-android#58]
Before moving to the integration of MS Intunes on mobile, we have a few queries.
Ours is a react native application that is already live on both google play store and app store.

It is possible that some of our clients might be using Azure AD, while others might not.
a) Will login of non-azure clients be affected adversely?
b) Is it possible to switch off the feature for certain clients even with Azure AD?
c) Will app protection policies (eg. prevention of File Sharing, download of files, saving files to a local device, or print screen) applied for a client with Azure AD affect non-azure AD Clients?

[https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#configure-azure-active-directory-authentication-library-adal]
Will prevention of File Sharing, print screen, copy-pasting of text, download of files, saving the file to a local device be supported with React Native? The extensions (for eg. share, action, Notification) are a part of a third-party library

Can we expect MS Intunes integration/ support for React Native in the near future?

**Comment by jarnakantaria-gep** [comment]
Hi,

Awaiting your response. This has come up as a new requirement from client and we have to provide timelines urgently. Please help us with quick revert.

**Comment by princejain-gep** [comment]
Hi,

Awaiting your response. We need to provide timeline for Client . 
Please reply quickly.

**Comment by annkiitagrawaal-gep** [comment]
Hi,

This is a very critical ask for us. We need your assistance to answer some important questions.

**Comment by joakley-msft** [comment]
Intune supports only Azure Active Directory sign-in. Your app may allow other forms of sign-in, but you will not be able to call MAM registration methods (via `MAMEnrollmentManager`) without an AAD login.

Our official stance on React Native is documented here https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#what-if-i-want-to-enable-an-app-with-intune-app-protection-but-it-is-not-using-a-supported-app-development-platform. In general, React Native should work (as long as you are using the native Gradle build, not pure Expo) but we don't make strong guarantees or provide any React Native tooling.
