### ISSUE TITLE
Data Transfer Exemptions/ContentProviders not functioning as expected

### ISSUE THREAD

**Issue by bblia** [msintuneappsdk/ms-intune-app-sdk-android#59]
We are unable to query content provider from Android Dialer unless Data Protection for "Send Org Data to Other Apps" is set to "All Apps". Exemptions are not working.

Our application is set up as a content provider for the Android Dialer to query caller ID matches against our app's directory of contact information. Based on the documentation [here](https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-android#data-transfer-exemptions), the phone app should already be granted full access although it is not a policy managed application. We have implemented our application based on the given documentation on [using Content Providers with Intune](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#content-providers). 

Is there an additional configuration necessary in the application policy for the Android phone app to query our content provider if "Send Org Data to Other Apps" is set to "Policy Managed Apps"? 

**To Reproduce**
1. Create a content provider in a test Intune application to provide caller ID information to the dialer. Example here: https://medium.com/@jmichaelis/android-your-users-as-caller-id-d446a58d9305
2. Set policy for "Send Org Data to Other Apps" to "All Apps"
3. Caller ID is should now be provided from your app for the inbound call.
4. Change setting to "Policy Managed Apps"
5. Caller ID does not work.

**Expected behavior:**
Based on the documentation, the phone app should be exempt from content provider restrictions / data sharing restrictions. It doesn't seem to be based on the above.

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3
 - OS: Android 10/API 29

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 7.01
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Kotlin/Java
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A
- Who is the customer? N/A
- Do you see a trend with it only being reproduced on a specific device? No.

**Comment by bblia** [comment]
Thank you for looking into it! We’ll try to validate the fix once it’s out.

**Comment by codylund** [comment]
This should be fixed with the latest version of the Company Portal available in the Google Play Store.
