### ISSUE TITLE
Intune Gradle plugin and Gradle cache

### ISSUE THREAD

**Issue by dexpota** [msintuneappsdk/ms-intune-app-sdk-android#60]
**Describe the bug:**
Intune Gradle plugin does not work well together with Gradle cache enabled. A deleted instrumentation test is still compiled and executed on the emulator when [Gradle caching](https://docs.gradle.org/current/userguide/build_cache.html) is enabled. Neither "Clean Project" nor "Invalidate Caches and Restart" fix the issue.

**To Reproduce**
1. Create a new Android project;
2. Setup Intune SDK with the project just created;
3. Enable Gradle caching by adding `org.gradle.caching=true` to `gradle.properties`;
4. Create a new instrumentation test, for example, a duplicate of `ExampleInstrumentedTest`, and let's called it `ExampleInstrumentedTestCopy`;
5. Execute all instrumented tests;
6. Delete the `ExampleInstrumentedTestCopy` test;
7. Clean the project;
8. Execute all instrumented tests;
9. The deleted instrumentation test will be executed;
10. The issue can be fixed by disabling Gradle caching;

**Expected behavior:**
The deleted instrumentation test should not be executed without disabling Gradle caching system.

**Screenshots:**

Before the deletion of the instrumentation test.
![Before the deletion of the instrumentation test](https://user-images.githubusercontent.com/7031675/109314796-1890fc00-784a-11eb-9f6a-1cefb4662020.png)

After the deletion of the instrumentation test.
![After the deletion of the instrumentation test](https://user-images.githubusercontent.com/7031675/109314845-2777ae80-784a-11eb-8465-3c0a1cf32075.png)

If we disable Gradle caching system and clean the project we restore the expected behavior.
![Screenshot 2021-02-26 at 15 52 13](https://user-images.githubusercontent.com/7031675/109315386-c69ca600-784a-11eb-9f5b-3470fdbdf745.png)

**Smartphone (please complete the following information):**
 - Device: Emulator;
 - OS: Android API 27;

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? **7.2.2**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? **Java**

**Additional context:**
I think this issue might be caused by some Gradle task that does not declare its input/output correctly. Thus Gradle is still using the result of the previous building of the project.

**Comment by joakley-msft** [comment]
This issue occurs only if the Intune plugin is in use?

I tried out these steps and am not able to reproduce this. I realize it's been some time. Are you still able to reproduce? If so, could you provide a project which reproduces the issue?

**Comment by dexpota** [comment]
I do not have an example at hand right now, I am going to try reproducing
the issue this weekend.

**Comment by dexpota** [comment]
This is a repository that reproduces this issue: https://github.com/dexpota/intune-gradle-issue

While working on it, I noticed that the issue is fixed by upgrading to `org.javassist:javassist:3.27.0-GA` without any need to upgrade the Intune Gradle plugin.

**Comment by joakley-msft** [comment]
Glad to hear it! 3.27 is the recommended/supported Javassist version.
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin
https://github.com/msintuneappsdk/ms-intune-app-sdk-android/blob/master/CHANGELOG.md#version-700
