### ISSUE TITLE
App Protection Policy UI not shown

### ISSUE THREAD

**Issue by knmueller** [msintuneappsdk/ms-intune-app-sdk-android#61]
**Describe the bug:**
The App Protection Policy UI is not always shown the first launch of the app. I am able to repro this only when the app is first launched *without* the Company Portal App installed. 

The "Go to Store" fragment pops up, which takes you directly to the Android app store to install the Company Portal App. Once installed, kill the app with the Intune SDK and re-open. The App Protection Policy screen does not show. I was able to repro this with the TaskR app *after* updating the MAMSDK libraries to the latest. The current MAMSDK libraries in the TaskR don't actually prompt you to require the company portal app.

If the app is then killed and relaunched again, the App Protection UI shows.

**To Reproduce**
1. Replace Microsoft.Intune.MAM.SDK.aar and com.microsoft.intune.mam.build.jar with the latest under app/MAMSDK of the TaskR app.  
2. Configure the TaskR app in the portal with App Protection Policy enabled to require an app PIN. 
3. Verify Company Portal app is not installed on device
4. Launch TaskR app and sign-in
5. Prompt will show - "... you must install the Microsoft Intune Company Portal app...". Click "Go To Store" and install the Company Portal app.
6. Kill TaskR app and relaunch it. 
7. App signs-in silently and no App Protection UI screen is shown.

**Expected behavior:**
After the Company Portal app is installed and the app is relaunched, the App Protection UI should show to create a PIN. 

**Screenshots and logs:**
Log attached.  
[app-launch-after-company-portal-install.txt](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/files/6207686/app-launch-after-company-portal-install.txt)

**Smartphone (please complete the following information):**
 - Device: Google Pixel 3a
 - OS: Android 11 Build number RQ2A.210305.006

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? **7.2.2**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?  TaskR app -- java
- For errors during build, does the app build without Intune SDK integration? N/A
- For errors post build, does the app launch without being Intune SDK integrated? N/A
- Who is the customer? N/A
- Do you see a trend with it only being reproduced on a specific device? Broken on Pixel 3a Android 11, 3a Emulator API 29, Pixel 2 Emulator API 28

**Additional context:**
On the first launch of the app after the Company Portal app is installed (in the repro scenario), I always see the following Company Portal stack trace. I don't see this stack trace at any other point:
```
11152 11278 E JavaBinder: *** Uncaught remote exception!  (Exceptions are not yet supported across processes.)
11152 11278 E JavaBinder: java.lang.RuntimeException: android.os.RemoteException: Unable to get WPJ device id
11152 11278 E JavaBinder: 	at android.os.Parcel.writeException(Parcel.java:2158)
11152 11278 E JavaBinder: 	at android.os.Binder.execTransactInternal(Binder.java:1178)
11152 11278 E JavaBinder: 	at android.os.Binder.execTransact(Binder.java:1123)
11152 11278 E JavaBinder: Caused by: android.os.RemoteException: Unable to get WPJ device id
11152 11278 E JavaBinder: 	at com.microsoft.windowsintune.companyportal.workplace.WorkplaceJoinManagerService$WPJManagerBinder.getDeviceId(WorkplaceJoinManagerService.java:90)
11152 11278 E JavaBinder: 	at com.microsoft.intune.companyportal.workplace.IWPJManagerService$Stub.onTransact(IWPJManagerService.java:67)
11152 11278 E JavaBinder: 	at android.os.Binder.execTransactInternal(Binder.java:1154)
11152 11278 E JavaBinder: 	... 1 more
```
MSAL config:
```
{
  "client_id" : <REDACTED>,
  "authorization_user_agent" : "DEFAULT",
  "redirect_uri" : "msauth://<REDACTED>",
  "broker_redirect_uri_registered": false,
  "multiple_clouds_supported": false,
  "authorities" : [
    {
      "type": "AAD",
      "authority_url": "https://login.microsoftonline.com/<REDACTED>"
    }
  ],
  "account_mode": "SINGLE",
  "logging": {
    "pii_enabled": true,
    "log_level": "VERBOSE",
    "logcat_enabled": true
  }
}
```

**Comment by joakley-msft** [comment]
This is expected by default as MAM enrollment is asynchronous. The mechanism to ensure that MAM policy is applied before the app can be used is APP CA. See https://docs.microsoft.com/en-us/mem/intune/protect/app-based-conditional-access-intune for an overview. See https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-protection-ca for directions on supporting APP CA in your app.
