### ISSUE TITLE
First Time Company Portal Installed Issue

### ISSUE THREAD

**Issue by RamitPahwa** [msintuneappsdk/ms-intune-app-sdk-android#62]
**Describe the bug:**
The issue arises when we start the enrolment in client application, but don't have the company portal installed upon which we receive a Notification in `MAMEnrollmentNotification` as `COMPANY_PORTAL_REQUIRED.upon` which we see the dialog which prompts us to install Company portal application ( by clicking on the **Go to Store**) (We call `unregisterAccountForMAM()`). We proceed to install the company portal application and then return back to our client to re initiate the `registerAccountForMAM()` API fo the authenticated account. Enrolment succeeds and policy are enforced.
Now the issue arrises when we "clear data" of the company portal application which should remove all protected content from clients application which is not the cases in this workflow.

Important point is that if we already have Company portal application installed and start the same enrolment process (which is successful) followed by clear data of company portal application. Account is removed automatically as silentTokenAquistion fails and throws an exception since we do not have account now which is expected.
Essentially this should have been the same in the above described scenario where we installed Company portal and returned and re started the process.
Additionally we see the Window prompting that the Protected data is now removed in both scenario.

**To Reproduce**
Steps to reproduce the behaviour:
1.Launch client app
2. start OneDrive Authentication using MSAL Library
"You must install the Microsoft Intune Company portal app" dialog is shown
3. Tap on "GO TO STORE" button and install the Company portal app from play store
4.T ap device back button after successful installation of company portal app
5. Launch Client app and OneDrive account is getting linked automatically and policies are applied
6.Clear company portal app data
**Expected behaviour:**
The Account should be removed, which is observed when Company portal is already installed. 

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**
 - Device: All Android Devices
 - OS: Android 10, 11 was tested

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? **7.2.2**
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Acrobat Android --java
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? NO
- Who is the customer? OneDrive Integration 
- Do you see a trend with it only being reproduced on a specific device? No

**Additional context:**

**Comment by joakley-msft** [comment]
Ramit and I have been discussing by email, closing here.

**Comment by knmueller** [comment]
@joakley-msft Was there a solution to this?
