### ISSUE TITLE
MAM Strict Mode check NON_INTEGRATED_ACTIVITY_LAUNCH failed

### ISSUE THREAD

**Issue by Hristiqnvelqkov** [msintuneappsdk/ms-intune-app-sdk-android#63]
Integrate Intune SDK
Enable MamStrictMode -> MAMStrictMode.enable()
Result -> MAM Strict Mode check NON_INTEGRATED_ACTIVITY_LAUNCH failed. Activity com.flowscape.atlas.launcher.LaunchActivity is not MAM-integrated and not excluded.

I cannot understand what this mean, I can't find anything in docs

*

**Comment by meghandaly** [comment]
The `NON_INTEGRATED_ACTIVITY_LAUCH` strict mode check indicates that an activity was launched which was not MAM-integrated and not explicitly excluded by build-plugin configuration.

For your specific app, this indicates that `com.flowscape.atlas.launcher.LaunchActivity` does not inherit from a MAM `Activity` variant and has not been explicitly called out in the configuration for the [gradle build plugin](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#gradle-build-plugin).

For example:
```
intunemam {
    excludeClasses = ['com.flowscape.atlas.launcher.LaunchActivity']
}
```

The resulting outcome is that policy will not be applied to the Activity and that may be undesired behavior.
