### ISSUE TITLE
not able to access calendar via intune integrated APP

### ISSUE THREAD

**Issue by tulika17** [msintuneappsdk/ms-intune-app-sdk-android#64]
**Describe the bug:**
I am working on app that is used by office employees where they can see calendar meetings also. I integrated the Intune SDK into my App and policies has been successfully imported into the device.for eg: I can't copy/paste from my App now , it asked to set a PIN etc. this clearly shows that policies are imported properly.

I am calling office 365 api to access the calendar of user in my APP. But I am not able to see calendar of user. After installing  and signIn outlook  into my device, I am able to see calendar in my APP also . I have installed company portal (WE).
I don't understand that why outlook app is necessary to get the calendar in my app. 

to get the Intune policies , I implemented below code

- first called sampleApp?.acquireToken(acquireTokenParam) to get MSFT token ,
-  after getting successful MSFT token I am registering account for MAM which calls the MAMAuthenticationCallback.

  mEnrollmentManager.registerAccountForMAM(
                    activeAccount!!.username,
                    activeAccount!!.id,
                    activeAccount!!.tenantId,
                    activeAccount!!.authority
                )

- In the MAMAuthenticationCallback -->acquireToken method , I am   acquiring token for MAM  by using the default scope of the passed resource id. 

- After then whenever I get the  MAMEnrollmentManager.Result.ENROLLMENT_SUCCEEDED , I called MSFT token again with scope as Calendars.Read
- if(result == MAMEnrollmentManager.Result.ENROLLMENT_SUCCEEDED){
                              sampleApp?.acquireTokenSilent(
                                        arrayOf( "Calendars.Read"),
                                        "authority")
                            }

Please let me know what to do next to see the meetings in my APP. Ultimate goal is to access the calendar without installing outlook app.

Also let me know the document link (  https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-ca-with-policy-assurance ) is related to APP CA.
Currently I am using registerAccountForMAM in the callback method after getting successful token from MSFT. I am not using remediateCompliance on Android.
Please let me know when to use  remediateCompliance on Android.

**Comment by tulika17** [comment]
I am waiting for the solution

**Comment by joakley-msft** [comment]
Hi tulika17, you say that you aren't able to see the calendar, but you don't say what call you're making to download the calendar or what error that call fails with.  Does acquiring the token with the Calendars.Read scope succeed or fail? If it fails, what error does it fail with?

**Comment by meghandaly** [comment]
This issue does not contain enough information for us to take direction action. We have instituted new practices for monitoring issues regularly and will be closing issues that are not updated within 30 days. Please re-open if this is still occurring and include the requested information.
