### ISSUE TITLE
How to make unified login flow to the mobile app.

### ISSUE THREAD

**Issue by wobo-swati** [msintuneappsdk/ms-intune-app-sdk-android#65]
Hi,

I'm not sure this is correct place to ask, but I'm looking for a solution for a problem we are facing.
In my app, which has it's own authentication flow to login the users and this is done using SSO. Some vendors of our app use Microsoft corporate accounts for SSO login. Now one vendor is asking us to integrate the MS Intune in the app so that they can apply the policy which they create for their org.

I have followed the guidelines and documentation from [here](https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android) and implemented.

But my question, I end up with two login flow in my app (one by our own login and another from ms Intune), so not sure whether it is correct behavior or not.

I could not find any api from MAM sdk which can communicate to our server. 

Is there a way we can unify a single login to our server and also apply policy to our app? Any help is appreciate. 
Any help is appreciated. 

Thanks.

**Comment by joakley-msft** [comment]
Intune supports only AAD authentication. Depending on your architecture and business needs, you could conceivably add AAD authentication as an option for your server, thus allowing a single login, but there is no mechanism to use a different form of authentication with Intune.
