### ISSUE TITLE
 Even through I write this in build classpath files("app/MAMSDK/com.microsoft.intune.mam.build.jar") still i get com.microsoft.intune.mam.build as not found. Kindly help

### ISSUE THREAD

**Issue by SowmyaAnand** [msintuneappsdk/ms-intune-app-sdk-android#71]
**Describe the bug:**

**To Reproduce**

**Expected behavior:**

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
- If your app is experiencing an issue during build, do you have error logs?
- If your app is experiencing an issue post build, do you have app logs for the crash itself?

**Smartphone (please complete the following information):**

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version?
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
- For errors during build, does the app build without Intune SDK integration?
- For errors post build, does the app launch without being Intune SDK integrated?
- Who is the customer?
- Do you see a trend with it only being reproduced on a specific device?

**Additional context:**

**Comment by meghandaly** [comment]
@SowmyaAnand Please fill out the issue template with additional information so that we may better diagnose the issue.
