### ISSUE TITLE
android:exported required when intent filters are present in Manifest - Android 12

### ISSUE THREAD

**Issue by javidran** [msintuneappsdk/ms-intune-app-sdk-android#72]
**Describe the bug:**
When the app targets API 30, the next error occurs when executing the app:

> Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl211025264.tmp/base.apk (at Binary XML file line #97): com.microsoft.intune.mam.client.service.MAMBackgroundReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

**To Reproduce**

1. Include intune aar package on the app dependencies.
2. Target API 31 on build.gradle
3. Execute App on Android 31 device/emulator.

**Expected behavior:**
The expected behavior is that the app at least initiates correctly.

**Screenshots and logs:**
- If applicable, add screenshots to help explain your problem. 
The log is enough.
- If your app is experiencing an issue during build, do you have error logs?
None
- If your app is experiencing an issue post build, do you have app logs for the crash itself?
The errores appears when installing the app on the device:
> Error: INSTALL_PARSE_FAILED_MANIFEST_MALFORMED: Failed parse during installPackageLI: /data/app/vmdl211025264.tmp/base.apk (at Binary XML file line #97): com.microsoft.intune.mam.client.service.MAMBackgroundReceiver: Targeting S+ (version 31 and above) requires that an explicit value for android:exported be defined when intent filters are present'

**Smartphone (please complete the following information):**
 - Device: Android Emulator API 31 Google Play
 - OS: Android 12 Beta 4

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 
Using version 7.0.1. We tried 7.6.0 too with the same result.
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? 
Java
- For errors during build, does the app build without Intune SDK integration?
Yes
- For errors post build, does the app launch without being Intune SDK integrated?
Yes
- Who is the customer?
Caixabank
- Do you see a trend with it only being reproduced on a specific device?
Every device running Android 12+

**Additional context:**
This bug is related with one of the Android 12 behavior changes listed on the official Android 12 Beta website: https://developer.android.com/about/versions/12/behavior-changes-12#exported

Exported attributes are now mandatory to be declared for every intent-filter. We updated the ones included in our app, but the libraries we are using also need to declare them if they use intent-filters too.

**Comment by svarnik** [comment]
I think MS will publish new SDK version with Android 12 support.

**Comment by meghandaly** [comment]
The SDK does not currently support Android 12. A future release will have Android 12 support.

**Comment by javidran** [comment]
Is there an expected date for its release?

**Comment by meghandaly** [comment]
Aye, we are targeting mid-September!

**Comment by javidran** [comment]
Any updates on this?

**Comment by meghandaly** [comment]
SDK 8.0 is now available!  [Version 8.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/8.0.0)
