### ISSUE TITLE
App crashes with INTUNE SDK integrated throws java.lang.RuntimeException: Unable to start activity ComponentInfo

### ISSUE THREAD

**Issue by franferns** [msintuneappsdk/ms-intune-app-sdk-android#75]
**Describe the bug:**
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fa.sd.net/com.fa.sd.net.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference

The app is integratd with the intune sdk and hosted on playstore. When installing the app while the intune company portal is NOT installed there is no error/exception thrown when we open the app.

However if the Company portal app is installed and then the app gets installed on open of the app it throws an exception.

Also when the app crashes, continously opening the app 6-7 times then gets the app to working.

TO reproduce the error once the app is made to work by continously opening go to app into and "Clear storage" open app the same error is thrown.

Also , While debugging the app no exception gets thrown. 

**To Reproduce**
1. Go to App When install along with the Intune Portal app on open of the app the app crashes continously open the app app works
2. Go to App Info and Clear Storage and re open the app the same error gets thrown

**Expected behavior:**
The app integrated with the Intune SDK needs to open without crashing the app.

**Screenshots and logs:**
--------- beginning of crash
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: FATAL EXCEPTION: main
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: Process: com.fa.sd.net, PID: 18264
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fa.sd.net/com.fa.sd.net.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7582)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.content.ContextWrapper.getOpPackageName(ContextWrapper.java:158)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.content.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:178)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices.<init>(MAMSystemServices.java:105)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.newInstance(MAMSystemServices_Factory.java:106)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.get(MAMSystemServices_Factory.java:80)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.get(MAMSystemServices_Factory.java:19)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.initialize(MAMClientImpl.java:304)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMClientSingletonImpl.ensureInitialized(MAMClientSingletonImpl.java:74)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.app.ActivityBehaviorImpl.attachBaseContext(ActivityBehaviorImpl.java:266)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at $Proxy5.attachBaseContext(Unknown Source)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at com.microsoft.intune.mam.client.app.MAMActivity.attachBaseContext(MAMActivity.java:58)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.Activity.attach(Activity.java:7728)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
09-07 23:50:53.032 1410404 18264 18264 E AndroidRuntime: 	... 11 more
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: FATAL EXCEPTION: main
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: Process: com.fa.sd.net, PID: 18483
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fa.sd.net/com.fa.sd.net.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3455)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3598)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2164)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7582)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getOpPackageName()' on a null object reference
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.content.ContextWrapper.getOpPackageName(ContextWrapper.java:158)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.content.ClipboardManager.addPrimaryClipChangedListener(ClipboardManager.java:178)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices.<init>(MAMSystemServices.java:105)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.newInstance(MAMSystemServices_Factory.java:106)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.get(MAMSystemServices_Factory.java:80)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMSystemServices_Factory.get(MAMSystemServices_Factory.java:19)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMClientImpl.initialize(MAMClientImpl.java:304)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.ipcclient.MAMClientSingletonImpl.ensureInitialized(MAMClientSingletonImpl.java:74)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.app.ActivityBehaviorImpl.attachBaseContext(ActivityBehaviorImpl.java:266)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.InterProxy$InterInvocationHandler.invoke(InterProxy.java:88)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at $Proxy5.attachBaseContext(Unknown Source)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at com.microsoft.intune.mam.client.app.MAMActivity.attachBaseContext(MAMActivity.java:58)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.Activity.attach(Activity.java:7728)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3409)
09-07 23:50:54.736 1410404 18483 18483 E AndroidRuntime: 	... 11 more

**Smartphone (please complete the following information):**
 - Device: Moto G 5G
 - OS: Android10

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Yes 
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? Cordova
- For errors during build, does the app build without Intune SDK integration? Yes
- For errors post build, does the app launch without being Intune SDK integrated? Yes
- Who is the customer? frontAvenue A/S
- Do you see a trend with it only being reproduced on a specific device? No 

**Additional context:**
Attached video of the crash and sample project in which the crash is observed

https://user-images.githubusercontent.com/779253/132874246-b5379ca1-48cd-49c2-81fd-d3b70cdb549f.mp4
https://drive.google.com/file/d/15Sshu1VVHyv9ifeRIE5_nfdiVyHfCu-0/view?usp=sharing

**Comment by joakley-msft** [comment]
Hi @franferns. The <application> element in your AndroidManifest.xml (app/src/main/AndroidManifest.xml in the zip you shared) does not have an android:name attribute and so will not refer to the correct application class. Please see the note on this in our docs at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#mamapplication

**Comment by franferns** [comment]
> Hi @franferns. The element in your AndroidManifest.xml (app/src/main/AndroidManifest.xml in the zip you shared) does not have an android:name attribute and so will not refer to the correct application class. Please see the note on this in our docs at https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#mamapplication

Thanks this solves the issue
