### ISSUE TITLE
Upgrading to 8.0.0 results in ClassCastException at Runtime

### ISSUE THREAD

**Issue by richakhanna** [msintuneappsdk/ms-intune-app-sdk-android#80]
While updating to Intune SDK and Intune gradle plugin from [7.6.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/7.6.0) to [8.0.0](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/releases/tag/8.0.0), I've noticed that it is crashing our release version of the application where R8 is enabled with the following stacktrace:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.Slack.intune, PID: 29685
    java.lang.ClassCastException: long[] cannot be cast to java.util.Map
        at com.slack.data.clog.SearcherMatchDetails.<init>(SearcherMatchDetails.java:6)
        at slack.services.autocomplete.impl.trackers.AutoCompleteTrackerImpl.trackResultSelected(AutoCompleteTrackerImpl.kt:41)
        at slack.services.slacktextview.SlackTextView$SlackOnItemClickListener.onItemClick(SlackTextView.kt:109)
```

In testing I found that if I rollback to the previous version of Intune SDK ` 7.6.0`, the app works. So, reporting it here that we aren't able to use version `8.0.0` because of this issue. Also, this problem only happens when R8 is enabled. Please take a look.

**Comment by meghandaly** [comment]
It appears this issue was ultimately an issue with R8 that has been addressed by Google: [java.lang.ClassCastException thrown in a class’s constructor in build minified by R8](https://issuetracker.google.com/issues/205205666?pli=1), closing.
