### ISSUE TITLE
Outlook for Android is not getting the proper permissions granted

### ISSUE THREAD

**Issue by mdurini-swisscom** [msintuneappsdk/ms-intune-app-sdk-android#82]
Hello, we configured an enrollment using the "Personal owned device with work profile" way and a device configuration profile with the option "Default app permissions" configured as "Auto grant". I was expecting to have the Outlook for Android application (installed as requested application and configured as managed app) eligible to access to the calendar permissions after the first login but this is not working (the calendar sync it not working anyway, as stated in [this](https://github.com/msintuneappsdk/ms-intune-app-sdk-android/issues/81) issue). I need to manually grant the permission to the app to see the option inside the application 

**Expected behavior:**
We would expect to see the permission granted as with other applications that are inside the work profile

**Smartphone:**
 - Device: Samsung A12 (same behavior also with other models / vendors)
 - OS: Android 11

**Comment by joakley-msft** [comment]
Hi @mdurini-swisscom this repo is for developers who integrate the Intune APP SDK for Android into their own applications. Further, the device management configuration of permissions does not go through the APP SDK. For other issues with Intune, you'll need to raise a support request to Microsoft through your company or organization. If you're not familiar with this process, please see https://docs.microsoft.com/mem/get-support
