### ISSUE TITLE
Android Auto not working after integrate this SDK

### ISSUE THREAD

**Issue by PeaceAllen** [msintuneappsdk/ms-intune-app-sdk-android#83]
**Describe the bug:**
Android Auto does not work after I integrate this SDK and install Company Portal App in my Android Phone.
when I uninstall the Company Portal App, it works again.

**To Reproduce**
my app is a audio player app, and support android auto function.  
after i integrate this SDK and enroll in Company portal app,  android auto could not work.
SDK version is 7.6.0.

**Comment by bannus** [comment]
Our SDK may block incoming our outgoing functionality depending on the policy you have configured. If you have configured policies that you expect to allow Android Auto to continue to function, please share your policy configuration and upload Company Portal logs after reproducing the issue:

* Open the Company Portal. If not logged in, press the "..." menu button in the top right.  If already logged in, press the hamburger icon in the top left.
* Click Help -> Email Support -> Upload Logs Only
* Share the Incident ID displayed here

**Comment by joakley-msft** [comment]
Last request for information was over a month ago without reply, closing. Please feel free to reactivate if further information becomes available.
