### ISSUE TITLE
Multi tenancy not supported

### ISSUE THREAD

**Issue by sandeepbhatia4922** [msintuneappsdk/ms-intune-app-sdk-android#84]
I have created a LOB app and implemented intune SDK. I have registered the app on azure portal and provided authentication, api permissions. Similarly deployed protection policies on https://endpoint.microsoft.com/#home. Now I am able to login through MSAL and register for MAM with my tenant. and fetching the protection policies I have deployed.

But if I want to login with other tenant which have also deployed policies for same LOB app then I am facing problem.

com.microsoft.identity.client.exception.MsalUiRequiredException: AADSTS65001: The user or administrator has not consented to use the application with ID 'e0a0e813-8123-**************' named '********'. Send an interactive authorization request for this user and resource.

I am using MSAL for authentication. But with different tenant ID token is not returned so I am unable to register for MAM.  This is the config file I am using for MSAL authentication -
`{
  "client_id": "e0a0e813-8123-4188**************",
  "authorization_user_agent": "DEFAULT",
  "redirect_uri": "msauth://com.************************",
  "authorities": [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMultipleOrgs",
        "tenant_id": "organizations"
      }
    }
  ]
}`

Kindly help immidiately.

**Comment by joakley-msft** [comment]
Please see https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-get-started#give-your-app-access-to-the-intune-app-protection-service-optional. The permissions you mentioned in your first paragraph must be granted in _each_ tenant which uses your app.

**Comment by sandeepbhatia4922** [comment]
thanks @joakley-msft 
now i am able to provide consent to app by other organisations. But it still working with manual approval of permission. As I grant permission on behalf of organisations through a prompt in app, access token not returned for MAM service.

But if I manually grant consent in azure active directory for enterprise app, it's working fine. I am attaching screenshot for both process of granting permission.
We need to grant permission through
![ConsentPermission](https://user-images.githubusercontent.com/46603588/144563537-d08a2fda-9481-4289-8e63-2ed2b3cc699a.jpg)
![manuallyconsent](https://user-images.githubusercontent.com/46603588/144563576-800730b4-f5ff-475b-b6e6-cb7bb02b5ea7.jpg)
 app prompt itself not manually by an IT admin. Kindly help.

**Comment by bannus** [comment]
@sandeepbhatia4922 My understanding is that this permission can only be granted in the admin console, and there is not a way to grant it via an app prompt. Can you elaborate on why the manual approval by IT admin does not meet your needs so we can better understand your issue?

**Comment by sandeepbhatia4922** [comment]
@bannus  Right, With IT admin's approval app is working fine. But then why app is prompting to ask grant permission for tenant?
Since it's confusing user as two time consent providing process on behalf of organisation, one from app and other by IT admin.

**Comment by joakley-msft** [comment]
If permission is not previously granted by the admin in the console then the app will prompt the user when launched. Only an admin is able to accept the permission on behalf of the organization. 

You said above " if I manually grant consent in azure active directory for enterprise app, it's working fine". If I'm understanding you correctly, you're seeing the expected behavior. The preferred path is for the admin to grant consent in Azure Active Directory before any users attempt to sign in.

**Comment by sandeepbhatia4922** [comment]
thanks @joakley-msft  for clarification
