### ISSUE TITLE
Registering Account for MAM always returns NOT_LICENSED

### ISSUE THREAD

**Issue by ajennings1990** [msintuneappsdk/ms-intune-app-sdk-android#86]
**Describe the bug:**
I am integrating the Android SDK (version 8.1.1) into our Android app following the documentation provided. 

I have managed to successfully integrate MSAL and complete the authentication flow and log into our domain to retrieve the MSAL account for my user (including access token). 
We then call "registerAccountForMAM" upon which the SDK displays the returned notification for enrolment and displays it in the Android Studio logs. This always returns the status NOT_LICENSED.

I have double checked all our configuration in the Azure Active Directory as well Microsoft Endpoint manager AND even been on several phone calls with Microsoft Endpoint Manager Support to try and diagnose any issues with their setup. However nothing was found (but can't be ruled out entirely at this point). The user is definitely showing with the Intune license applied/configured. 

The Company portal app is installed. I have tried this with both no Device Enrolment and full Device Enrolment with no change. Our end goal as a business is to provide only App Enrolment *without* Device Enrolment. This has been achieved (with the same tenant id/client id/user) on iOS already. 

**To Reproduce**
- Launch App
- Authenticate with MSAL using 'acquireToken'
- Complete MSAL authentication 
- Register with Intune using 'registerAccountForMAM'
- Logs show NOT_LICENSED returned as enrolment result

**Expected behavior:**
- Expect user to be enrolled successfully and app protection polices to be applied 

**Screenshots and logs:**
This is our `msal_config.json` file:

     {
      "client_id" : "<redacted>",
      "redirect_uri" : "msauth://<redacted - package name>/<redacted - percent encoded signature hash>",
      "authorities" : [
    {
      "type": "AAD",
      "audience": {
        "type": "AzureADMyOrg",
        "tenant_id": "redacted"
      }
    }
     ],
      "broker_redirect_uri_registered": false,
      "authorization_user_agent": "WEBVIEW", // tried DEFAULT as well
      "multiple_clouds_supported": false,
    "http": {
     "connect_timeout": 10000,
     "read_timeout": 30000
     },
    "logging": {
      "pii_enabled": false,
      "log_level": "WARNING",
      "logcat_enabled": true
    },
    "shared_device_mode_supported": false,
    "account_mode": "SINGLE",
    "browser_safelist": [ <default implementation> ] 

Creating application - called inside provided `MSALUtil` file:
`PublicClientApplication.create(appContext, R.raw.msal_config, listener)`

See below our method for acquiring the token interactively:
 
    @WorkerThread
    @Throws(MsalException::class, InterruptedException::class)
    fun acquireToken(
        romActivity: Activity,
        scopes: Array<String?>,
        loginHint: String?,
        callback: AuthenticationCallback
    ) {
        val params = AcquireTokenParameters.Builder()
            .withScopes(listOf(*scopes))
            .withCallback(callback)
            .startAuthorizationFromActivity(fromActivity)
            .withLoginHint(loginHint)
            .build()
        mMsalClientApplication!!.acquireToken(params)
    }

See below our Callback handler:

    private class DefaultAuthenticationCallback(val enrollmentManager: MAMEnrollmentManager):
        AuthenticationCallback,
        MAMServiceAuthenticationCallback {

        var accessToken: String? = null

        // AuthenticationCallback

        override fun onSuccess(authenticationResult: IAuthenticationResult?) {
            print("SUCCESS!!")
            accessToken = authenticationResult?.accessToken

            val account: IAccount = authenticationResult?.account!!

            enrollmentManager.registerAccountForMAM(
                account.username,
                account.id,
                account.tenantId,
                account.authority
            )
        }

        override fun onError(exception: MsalException?) {
            print(exception?.localizedMessage)
        }

        override fun onCancel() {
            // TODO: AJ - Handle this
        }

        // MAMServiceAuthenticationCallback

        override fun acquireToken(p0: String, p1: String, p2: String): String? {
            return accessToken
        }

    }

These are the logs shown in the Console in Android Studio:

     getAccountInfo() called for account that is not registered: andy.jennings@interactsoftware.com
     I/MAMWEAccountRegistry: registering account andy.jennings@interactsoftware.com
     I/AMEnrollmentManagerImpl: attempting MAM-WE V2 enrollment for: andy.jennings@interactsoftware.com; MAM-CA flow: false
     I/MAMWERetrySchedulerImpl: removing any remaining scheduled tasks for andy.jennings@interactsoftware.com
     I/SessionDurationStore: Setting telemetry session [81475a9e-e1f8-43ba-8858-408be1b45879] start time: 83073660
     I/KnownClouds: defaulting to worldwide
     I/AuthCallbackUtils: Calling app's acquireToken callback.
     V/FA: Inactivity, disconnecting from the service
     I/a: Running background check
     W/.interact.debu: Couldn't lock the profile file /data/misc/profiles/cur/0/com.interactgo.interact.debug/primary.prof: Failed to open file '/data/misc/profiles/cur/0/<redacted>/primary.prof': Permission denied
     W/.interact.debu: Could not forcefully load profile /data/misc/profiles/cur/0/<redacted>/primary.prof
     I/a: Running background check
     I/a: Running background check
     I/AuthCallbackUtils: App's acquireToken callback successfully returned a token.
     I/TelemetryLoggerImpl: {"SERVICE_NAME":"ADAL","START_TIME":83073686,"MAM_APP_ID":"<redacted>","SUCCEEDED":true,"OPERATION_NAME":"GetMAMServiceToken","MAM_APP_VERSION":"2.18.0","EVENT_CLASS":"com.microsoft.intune.mam.client.telemetry.events.ServiceRequestEvent","DEVICE_BRAND":"samsung","AAD_TENANT_     ID":"<redacted>","SESSION_ID":"81475a9e-e1f8-43ba-8858-408be1b45879","DURATION":303431,"AUTH_TYPE":"APIV2"}
     I/AMEnrollmentManagerImpl: MAM Service enrollment for com.interactgo.interact.debug, identity andy.jennings@interactsoftware.com, returned result: PENDING
     I/.MAMNotificationHandler: Delivering MAM_ENROLLMENT_RESULT notification
     I/MAMWEAccountRegistry: updating account andy.jennings@interactsoftware.com with status NOT_LICENSED
     I/MAMWERetrySchedulerImpl: For NOT_LICENSED MAM-WE account User-1100323144 using retry interval 43200000 ms (12 hours)
     I/MAMWERetrySchedulerImpl: scheduling MAM-WE enrollment retry in 43200000 ms (12 hours) for andy.jennings@interactsoftware.com with status NOT_LICENSED
     I/MAMWERetrySchedulerImpl: scheduling enrollment retry task for andy.jennings@interactsoftware.com due at 2021-12-02 21:51:23.
     I/MAMWERetrySchedulerImpl: task thread got 0 task(s) to execute.
     I/MAMWERetrySchedulerImpl: task thread waiting for tasks.
     I/entNotificationReceiver: Received MAM enrollment result for package com.interactgo.interact.debug, user andy.jennings@interactsoftware.com: NOT_LICENSED
     I/TelemetryLoggerImpl: {"MAM_APP_ID":"redacted","MAM_APP_VERSION":"2.18.0","ERROR":"NONE_KNOWN","EVENT_CLASS":"com.microsoft.intune.mam.client.telemetry.events.ScenarioEvent","DEVICE_BRAND":"samsung","SCENARIO":"ENROLLMENT","AAD_TENANT_ID":"<redacted>","SESSION_ID":"81475a9e-e1f8-43ba-8858-408be1b45879","RESULT":"NOT_LICENSED","DURATION":305119,"STOP_TIME":83378783}

**Smartphone (please complete the following information):**
 - Device / OS: 
 - Nokia 3.4 - Android 11
 - Samsung Galaxy S8 - Android 9 

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? 
- 8.1.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)?
-  Kotlin / Java project with Android Studio
- For errors during build, does the app build without Intune SDK integration?
- Yes
- For errors post build, does the app launch without being Intune SDK integrated?
- Yes
- Do you see a trend with it only being reproduced on a specific device?
- No, multiple devices

**Additional context:**
We are using requesting the MSAL access token with a custom scope - however this is correctly setup in the portal with no errors being shown in the logs regarding scopes. 

The only other error I've seen (in the device logs) that _could_ be relevant (maybe) is this:
`2021-11-24T14:51:39.2950000	ERR_	com.microsoft.omadm.apppolicy.mamservice.MAMServiceEnrollmentTask	19080	01201	Enrollment failed for package com.interactgo.interact.debug, user User-1100323144; No URL for MAMService.`

The next two lines of logs after the one above are:
`2021-11-24T14:51:39.2970000	INFO	com.microsoft.omadm.apppolicy.mamservice.MAMServiceEnrollmentTask	19080	01201	Completed MAMServiceEnrollmentTask for package com.interactgo.interact.debug, user User-1100323144. OperationSessionGuid: 1df121e7-745e-4ee9-aa56-8407ce288739.
2021-11-24T14:51:39.3080000	INFO	com.microsoft.omadm.apppolicy.mamservice.MAMServiceEnrollmentTask	19080	01201	Sending enrollment result notification for package: com.interactgo.interact.debug, user User-1100323144: NOT_LICENSED`

Thanks!

**Comment by bannus** [comment]
Hi @ajennings1990, can you confirm that this user and app (`com.interactgo.interact.debug`) is targeted with App Protection Policy in the MEM console?

**Comment by ajennings1990** [comment]
@bannus I can confirm that they are, yes.

I did manage to resolve this issue by removing the following from my msal_config.json file
`"http": {
       "connect_timeout": 10000,
    "read_timeout": 30000
  },
  "logging": {
    "pii_enabled": false,
    "log_level": "WARNING",
    "logcat_enabled": true
  },
  "shared_device_mode_supported": false,
  "browser_safelist": [ <default values from documentation> ]`
  
Then Enrolment succeeded. I have yet had time to experiment with which part of those json values caused my issue specifically. 

However I'm now experiencing a new issue with 
`com.microsoft.identity.client.exception.MsalClientException: Attempt to invoke virtual method 'boolean android.content.IntentFilter.hasAction(java.lang.String)' on a null object reference`

...but I appreciate that's probably unrelated so feel free to close this ticket if desired.

**Comment by bannus** [comment]
@ajennings1990 OK, thanks for the update. I'll close this issue. If you determine that a particular MSAL setting was causing your MAM enrollment issue, please let us know so we can investigate.

**Comment by ajennings1990** [comment]
@bannus Spoke too soon. I'm getting that issue again. Seems to occur on my Nokia device running Android 11. 
My Samsung running Android 9 manages to enrol just produces that new error (in my last message).

**Comment by bannus** [comment]
@ajennings1990 If you have a consistent repro of the original issue, would you upload Company Portal logs immediately after reproducing:

* Open the Company Portal. If not logged in, press the "..." menu button in the top right. If already logged in, press the hamburger icon in the top left.
* Click Help -> Email Support -> Upload Logs Only
* Share the Incident ID displayed here

**Comment by meghandaly** [comment]
@ajennings1990 is this still presenting as an issue on the Nokia device running Android 11? If so, can you please upload Company Portal logs as Bannus suggested to help us with our investigation?

**Comment by joakley-msft** [comment]
Last request for information was over a month ago without response, closing. Please feel free to reactivate if further information becomes available.
