### ISSUE TITLE
Not getting the Install Microsoft Intune Company Portal app Popup dialog message

### ISSUE THREAD

**Issue by anandayyanar3450** [msintuneappsdk/ms-intune-app-sdk-android#91]
I have configured the Intune company portal in my app, although I am getting Device health check up screen when I install the app from the company portal, but suppose users who dont have the comapny portal app installed, I am not getting the Install Microsoft Intune Company Portal app pop up dialog msg ie [https://filestore.community.support.microsoft.com/api/images/4efb19b1-ce70-482c-a61c-73749a65984b?upload=true](url)

Should I manually check it or the Intune Portal does it, because I am getting AUTHORIZATION_NEEDED msg
Kindly assist

**Comment by boyzhang-msft** [comment]
Hi @anandayyanar3450, thanks for reporting this. You shouldn't need to any manual work get the "Install Company Portal" screen, if the enrolled user (user signed into the app) is targeted with MAM policy, you should get this prompt for free after correctly integrating MAM SDK in your app.

Some clarification questions please:
- Is your app a multi-identity app?
- Have you followed the steps in the integration guide here https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android? Specifically, the code changes needed in your app listed in this section? https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#app-protection-policy-without-device-enrollment 

The AUTHORIZATION_NEEDED notification is sent to the app when the app doesn't return a valid AAD token in the acquireToken call so MAM enrollment failed and MAM didn't prompt you to install Company Portal. For how to address this issue, please read more on this section and let us know if it works:
https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#authentication

**Comment by bannus** [comment]
Closing as we did not receive a response for over 30 days.
