### ISSUE TITLE
Not able to skip brokered auth or use com.microsoft.intune.mam.aad.NonBrokerRedirectURI

### ISSUE THREAD

**Issue by mlynch** [msintuneappsdk/ms-intune-app-sdk-android#92]
**Describe the bug:**

When using MSAL directly inside of an app with the Android Intune App SDK, the auth broker is always invoked even when calling `acquireTokenSilentAsync` and setting the following configuration options to skip the brokered auth flow: https://docs.microsoft.com/en-us/mem/intune/developer/app-sdk-android#configure-microsoft-authentication-library-msal

**To Reproduce**
1. Install MSAL and the Intune App SDK into an app
2. Disable brokered auth using `com.microsoft.intune.mam.aad.SkipBroker="true"` and setting `com.microsoft.intune.mam.aad.NonBrokerRedirectURI` and placing those `<meta-data` tags inside of the `<application` tag in `AndroidManifest.xml`.
3. Call MSAL `acquireToken` and `acquireTokenSilent` flows
4. Notice that the broker is still used even with this setting

**Expected behavior:**

The developer can skip enrollment and only acquire a token to enable a better/faster development mode

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? Intune App SDK 8.3.0
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? [Capacitor](https://capacitorjs.com/) using the Java Intune App SDK
- Who is the customer? Large European Bank

**Additional context:**

My hunch is there's some Azure configuration required here but the docs really aren't clear on this front. The customer wants to skip brokered auth in development mode and they are not enrolling the dev device but just want to get tokens from MSAL

**Comment by joakley-msft** [comment]
Hi @mlynch, my apologies that you didn't get a response sooner. The Intune meta-data tags that you set affect only Intune's authentication usage and expectations. They don't control MSAL or have any bearing on the tokens that your app requests through calls to MSAL APIs. 

If you want the broker not to be used in these calls, you need to edit your MSAL configuration JSON. Specifically, you need to make sure you do *not* follow the directions here https://docs.microsoft.com/en-us/azure/active-directory/develop/msal-android-single-sign-on#configure-msal-to-use-a-broker and instead set `broker_redirect_uri_registered` to false. If you encounter further issues with your MSAL calls, I'd recommend raising an issue on https://github.com/AzureAD/microsoft-authentication-library-for-android/issues
