### ISSUE TITLE
Unsafe Cipher Mode In Google Play Store

### ISSUE THREAD

**Issue by ajennings1990** [msintuneappsdk/ms-intune-app-sdk-android#94]
**Describe the bug:**
We have integrated the Intune SDK into our Android app and when we've submitted it to the Google Play Store it's showing the following error.
<img width="783" alt="Screenshot 2022-01-27 at 11 34 06" src="https://user-images.githubusercontent.com/28726801/151526328-f3fdf703-b6d8-4471-b140-96d3f2862e31.png">

**To Reproduce**
- Integrate SDK
- Upload Release build to Google Play Store
- Promote Release to Production
- Error appears in Release Overview

**Expected behavior:**
No errors to appear. 

**Intune App SDK for Android (please complete the following information):**
- What version of the Intune SDK are you using? Are you using the latest version? --> 8.1.1
- What platform is your app based in (Java, Xamarin based, Cordova, etc)? --> Android / Kotlin
- For errors during build, does the app build without Intune SDK integration? --> Project Builds okay
- For errors post build, does the app launch without being Intune SDK integrated? --> Project Launches okay

**Additional context:**
The app is able to be successfully promoted to Production so the error does not hold up release but us and our White Label clients are concerned about the error appearing in the console and would like to understand it more and if there is a way to prevent it appearing. Thanks!

**Comment by joakley-msft** [comment]
You will need to work with the ADAL library on this, or convert to the newer MSAL library. The class shown in that screenshot is _not_ part of the Intune APP SDK, nor does our SDK introduce a dependency on it.

**Comment by joakley-msft** [comment]
Note that ADAL can be found on Github here: https://github.com/AzureAD/azure-activedirectory-library-for-android
