### ISSUE TITLE
 About Intune's MAMStartupActivity

### ISSUE THREAD

**Issue by pa-y-omura** [msintuneappsdk/ms-intune-app-sdk-android#98]
As a normal operation when the restrictions by Intune are properly reflected in the application, I think that MAMStartupActivity will appear at the first startup, but regarding the appearance timing of this screen, the following two situations are confirmed.

- First-time installation app
→ After displaying the startup screen (splash screen) of our application, MAMStartupActivity starts.

- Installed apps from the second time onwards
→ After displaying MAMStartupActivity, the startup screen (splash screen) of our application starts.

 
In this case, the expected behavior is the display order of "installed apps from the second time onward", but why is the timing when MAMStartupActivity appears slightly different only for the first installed app?

### Definition of the first-time installation application

1. Install the portal app

2. Sign in to the portal app

3. After signing in, the corresponding Intune app to be installed for the first time via the portal app

### Definition of apps installed from the second time onwards
If you uninstall the above app and then install the same app again,all of them will be installed apps from the second time onward,regardless of the number of installations.

**Comment by msft-cofitz** [comment]
The MAM screens will appear based on policy arriving on the device and some different timers. The following resources should help explain the behavior you are seeing
- https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-delivery and the 
- https://docs.microsoft.com/en-us/mem/intune/apps/mam-faq#when-is-the-user-prompted-to-enter-their-pin
- "Recheck the access requirements" https://docs.microsoft.com/en-us/mem/intune/apps/app-protection-policy-settings-android
